/**
 * Golden-master regression suite (Road to Worlds Phase 0).
 *
 * Locks the EXACT random-draw order and outcomes of the shared sim pipeline
 * (simulateSeries → swiss → playoffs) on fixed seeds and dataset-free fake
 * teams, so any career-mode refactor that accidentally adds/removes/reorders
 * an rng call in shared code fails loudly here — before it silently knocks
 * the fixed-seed challenges/daily out of band.
 *
 * POLICY: the expected values below are only regenerated by an intentional,
 * CHANGELOG-documented decision — never to "fix CI". To regenerate, flip
 * PRINT_GOLDENS to true, run this file, and paste the logged values.
 */

import { describe, expect, it } from "vitest";
import { createRng } from "@/lib/rng";
import { simulateSeries } from "./match";
import { createPlayoffs, playPlayoffRound } from "./playoffs";
import { createSwissState, playSwissRound, seedsFromSwiss } from "./swiss";
import type { Stats, TournamentState, TournamentTeam } from "./types";

const PRINT_GOLDENS = false;

function fakeTeam(id: string, rating: number, statsShift = 0): TournamentTeam {
  const stat = (v: number) => Math.min(99, Math.max(60, v));
  const stats: Stats = {
    offense: stat(rating + statsShift),
    defense: stat(rating - statsShift),
    mechanics: stat(rating),
    consistency: stat(rating),
    experience: stat(rating),
    clutch: stat(rating),
  };
  return {
    id,
    name: id,
    isUser: id === "user",
    region: "EU",
    rating: {
      avgPlayerOverall: rating,
      coachMod: 0,
      subMod: 0,
      orgMod: 0,
      chemMod: 0,
      specialMod: 0,
      difficultyShift: 0,
      total: rating,
    },
    chemistry: { raw: 0, max: 10, percent: 0, tier: "Poor", items: [] },
    stats,
    specialIds: [],
    playerNames: [`${id}-a`, `${id}-b`, `${id}-c`],
    orgId: id,
  };
}

function fixedField(): Record<string, TournamentTeam> {
  const teams: Record<string, TournamentTeam> = {};
  // 16 teams, ratings 92.5 down to 81.25 — deterministic construction, no dataset.
  for (let i = 0; i < 16; i++) {
    const id = i === 0 ? "user" : `t${String(i).padStart(2, "0")}`;
    teams[id] = fakeTeam(id, 92.5 - i * 0.75, (i % 3) - 1);
  }
  return teams;
}

/** Runs a full Swiss → double-elim tournament on a fixed seed; returns a compact signature. */
function runFullTournament(seed: number): {
  champion: string;
  rngEnd: number;
  swissWinners: string[];
  gfScore: [number, number];
} {
  const rng = createRng(seed);
  const teams = fixedField();
  let state: TournamentState = {
    teams,
    swiss: createSwissState(Object.keys(teams), rng),
    playoffs: null,
    stage: "swiss",
    userEliminated: false,
  };
  let guard = 0;
  while (!state.swiss.finished && guard++ < 8) {
    state = { ...state, swiss: playSwissRound(state.swiss, teams, "normal", rng) };
  }
  const seeds = seedsFromSwiss(state.swiss, teams);
  let playoffs = createPlayoffs(seeds);
  guard = 0;
  while (!playoffs.finished && guard++ < 12) {
    playoffs = playPlayoffRound(playoffs, teams, "normal", rng);
  }
  const gf = playoffs.rounds[playoffs.rounds.length - 1].series[0];
  return {
    champion: playoffs.championTeamId!,
    rngEnd: rng.state,
    swissWinners: state.swiss.records
      .filter((r) => r.status === "advanced")
      .map((r) => r.teamId)
      .sort(),
    gfScore: gf.score,
  };
}

describe("golden master — shared sim pipeline draw order", () => {
  it("simulateSeries produces byte-identical results on fixed seeds", () => {
    const a = fakeTeam("user", 90);
    const b = fakeTeam("opp", 88, 1);
    const sig = [1234, 987654, 424242].map((seed) => {
      const rng = createRng(seed);
      const s = simulateSeries(a, b, { bestOf: 7, stage: "playoff", difficulty: "hard" }, rng);
      return `${s.winnerTeamId}:${s.score[0]}-${s.score[1]}:${s.games.length}:${rng.state}`;
    });
    if (PRINT_GOLDENS) console.log("series goldens:", JSON.stringify(sig));
    expect(sig).toEqual([
      "opp:0-4:4:248189722",
      "user:4-0:4:249176142",
      "user:4-0:4:1448342873",
    ]);
  });

  it("full Swiss → double-elim runs are byte-identical on fixed seeds", () => {
    const sig = [20260709, 555555].map((seed) => {
      const r = runFullTournament(seed);
      return `${r.champion}|${r.gfScore[0]}-${r.gfScore[1]}|${r.rngEnd}|${r.swissWinners.join(",")}`;
    });
    if (PRINT_GOLDENS) console.log("tournament goldens:", JSON.stringify(sig));
    expect(sig).toEqual([
      "user|4-0|105101394|t01,t02,t03,t04,t05,t06,t09,user",
      "user|4-0|3252150890|t01,t02,t03,t04,t05,t07,t09,user",
    ]);
  });
});
