/**
 * PT-BR dictionary — mirrors the shape of `copy.en.ts` exactly.
 * Tone: narração de transmissão / análise pós-jogo (esports BR). Termos que a
 * comunidade brasileira de Rocket League costuma manter em inglês ficam como
 * estão (draft, reroll, run, overall, clutch, OT, playoffs, MVP).
 */

import type { Copy } from "./copy.en";

export const PT: Copy = {
  APP: {
    name: "Rocket Draft",
    tagline: "Drafte a história. Sobreviva à chave.",
    description:
      "Um jogo fan-made e gratuito de draft do Rocket League esports. Monte um elenco com lineups icônicas da RLCS, colecione cartas especiais lendárias e sobreviva a um torneio no estilo RLCS.",
    disclaimer:
      "Projeto fan-made, sem fins lucrativos, para fins educativos. Não afiliado à Psyonix, Epic Games ou qualquer organização de esports. Rocket League é marca registrada de seus respectivos donos.",
  },

  NAV: {
    home: "Início",
    play: "Jogar",
    collection: "Coleção",
    profile: "Perfil",
    settings: "Config",
  },

  HOME: {
    playClassic: "Draft Clássico",
    playClassicDesc: "3 jogadores, técnico, reserva e org. Suíça e playoffs de dupla eliminação.",
    quickDraft: "Draft Rápido",
    quickDraftDesc: "Só jogadores, chave curta. Feito para partidas rápidas.",
    daily: "Desafio Diário",
    dailyDesc: "Um draft com seed por dia, igual para todos.",
    dailyPlay: "Jogar o desafio de hoje",
    dailyVictory: "Vitória",
    dailyDefeat: "Derrota",
    dailyComeBack: "Volte amanhã para um novo desafio.",
    dailyStreak: (n: number) => `${n} vitórias seguidas`,
    comingSoon: "Em breve",
    collection: "Coleção",
    collectionDesc: "Cartas especiais que você desbloqueou nas suas runs.",
    collectionLocked: "Bloqueada — desbloqueia no Bronze",
    achievements: "Conquistas",
    achievementsDesc: "Feitos para perseguir em cada run.",
    profile: "Perfil",
    profileDesc: "Rank, XP e histórico de runs.",
    howToPlay: "Como jogar",
    joinDiscord: "Entrar no Discord",
    followTwitter: "Seguir no X",
    support: "Me pague um café",
    liveBadge: "No ar",
    playNow: "Jogar agora →",
    runs: (n: number) => `${n} ${n === 1 ? "run" : "runs"}`,
    titles: (n: number) => `${n} títulos`,
  },

  HOME_SEO: {
    heading: "Um jogo de draft da RLCS, gratuito e feito da história do Rocket League esports",
    intro:
      "Rocket Draft é um jogo de draft da RLCS gratuito e fan-made — parte roster builder, parte quiz de história do Rocket League esports, parte simulador de torneio. Drafte um time com lineups reais da RLCS de 2016 até hoje, construa chemistry, colecione cartas especiais de momentos lendários e percorra uma chave no estilo RLCS até o título.",
    sections: [
      {
        id: "how-it-works",
        title: "Como funciona o draft da RLCS",
        body: "A cada rodada entra uma lineup real e histórica da RLCS. Pegue uma única carta — um jogador, o técnico, o reserva ou a organização — até fechar um elenco de três jogadores, técnico, reserva e org. Junte mesmo país, mesma organização ou a mesma lineup e sua chemistry sobe, então um time coeso pode derrubar um mix de estrelas mais bem avaliado. Aí o torneio roda sozinho: fase suíça e playoffs de dupla eliminação, igual à RLCS de verdade.",
      },
      {
        id: "modes",
        title: "Três formas de draftar",
        body: "O Draft Clássico é a experiência completa — seis slots, suíça e dupla eliminação. O Draft Rápido é só jogadores, com uma chave curta para uma partida ligeira. O Desafio Diário é um draft com seed por dia, igual para todo mundo, com uma streak para defender. São quatro dificuldades, e vencer no Hard libera o Legacy — um gauntlet histórico de elencos campeões com os overalls escondidos.",
      },
      {
        id: "special-cards",
        title: "Cartas especiais da história da RLCS",
        body: "Além das cartas base do elenco, o Rocket Draft esconde dezenas de cartas especiais ligadas a momentos inesquecíveis do Rocket League esports — MVPs de Worlds e Majors, jogadores lendários e jogadas icônicas. Drafte uma, termine a run vencendo ou perdendo, e ela fica desbloqueada na sua coleção para sempre. A caçada faz parte do draft: uma única especial pode virar uma série.",
      },
      {
        id: "regions",
        title: "Bancos regionais — América do Sul & SAM",
        body: "O Draft Regional limita o pool a uma cena inteira — os times de Mundial mais o Top 8 regional que nunca chegou a um Worlds. A América do Sul (SAM) já está no ar, com um elenco pesquisado à mão de times brasileiros e sul-americanos, heróis locais e azarões cult que você não vê no draft mundial. Mais regiões estão a caminho.",
      },
      {
        id: "ratings",
        title: "Ratings revisados à mão e transparentes",
        body: "Cada overall é revisado à mão, não tirado de uma única linha de estatística — desempenho individual, resultados e contexto histórico entram na conta, e cartas especiais podem subir acima das versões base. A gente publica a metodologia para os ratings ficarem honestos e a comunidade poder contestar.",
      },
    ],
    links: {
      heading: "Explore o Rocket Draft",
      howToPlay: "Aprenda como funciona o draft da RLCS",
      ratings: "Leia a metodologia dos ratings",
      specialCards: "Veja as cartas especiais da RLCS",
      strategy: "Leia o guia de estratégia do Rocket Draft",
      sam: "Jogue o draft SAM de Rocket League",
      faq: "Perguntas frequentes",
      about: "Sobre o projeto",
      play: "Jogue o jogo de draft da RLCS",
    },
  },

  NAV_UI: {
    backToMenu: "Voltar ao menu",
    changelog: "Novidades",
    privacy: "Privacidade",
    howToPlay: "Como jogar",
    about: "Sobre",
    faq: "FAQ",
    discord: "Discord",
    support: "Apoiar o projeto",
    madeBy: "Feito por",
    inspiredBy: "Inspirado em",
    by: "por",
    balancedBy: "Overalls balanceados por",
  },

  RUN_UI: {
    reset: "Resetar run",
    resetTitle: "Resetar esta run?",
    resetBody:
      "Seu draft e progresso no torneio serão descartados e um novo draft começa na mesma dificuldade.",
    resetConfirm: "Resetar run",
    resetCancel: "Continuar jogando",
    phaseDraft: "Draft",
    phaseReview: "Revisão",
    phaseTournament: "Torneio",
    phaseResults: "Resultados",
    hiddenOvr: "OVR oculto",
  },

  SETUP: {
    title: "Configuração da Partida",
    subtitle:
      "Escolha uma dificuldade. O pool do draft é sempre totalmente aleatório — a dificuldade muda o torneio, não a sua sorte.",
    difficulty: "Dificuldade",
    showOverall: "Mostrar overalls durante o draft",
    showOverallHint:
      "Desligue para draftar só no conhecimento. Os overalls são revelados na tela de resultados.",
    overallLocked: "Travado oculto nesta dificuldade",
    rerolls: (n: number) => (n === 1 ? "1 reroll" : `${n} rerolls`),
    start: "Começar Draft",
    back: "Voltar ao menu",
    legacyLocked: "Vença um torneio no Difícil para desbloquear o Legacy.",
    hardLocked: "Chegue ao Prata para desbloquear o Difícil.",
    mode: "Modo de jogo",
    modeClassic: "Draft Clássico",
    modeClassicHint: "6 vagas · suíça + playoffs de dupla eliminação",
    modeQuick: "Draft Rápido",
    modeQuickHint: "só 3 jogadores · chave direta de 8 times",
    ovrOptional: "OVR opcional",
    ovrHidden: "OVR oculto",
    selected: "Selecionado",
    legacyBadge: "Gauntlet histórico",
    region: "Região",
    regionHint: "Trave sua run em uma região inteira — ou jogue mundial.",
    regionWorldwide: "Mundial",
    regionWorldwideHint: "Todos os times do Mundial da RLCS",
    regionComingSoon: "Em Breve",
    regionLockedBadge: "Região travada",
    regionDescWorldwide:
      "Todos os times do Mundial da RLCS. Toque numa região para travar o draft nela — por enquanto só a SAM está disponível, mais em breve.",
    regionDescLocked: (region: string) =>
      `Só ${region} — um pool mais profundo, que inclui times que nunca chegaram ao Mundial.`,
    regionNames: {
      NA: "América do Norte", EU: "Europa", SAM: "América do Sul", MENA: "MENA",
      OCE: "Oceania", APAC: "APAC", SSA: "África Subsaariana",
    } as Record<string, string>,
  },

  DIFFICULTY_LABELS: {
    easy: { label: "Fácil", tagline: "Aprenda o ritmo. Variância perdoadora, chave mais amigável." },
    normal: { label: "Normal", tagline: "A experiência RLCS padrão. Campo equilibrado." },
    hard: { label: "Difícil", tagline: "Overalls ocultos. Campo mais forte. Conhecimento vence." },
    legacy: { label: "Legacy", tagline: "Um gauntlet histórico de elencos campeões." },
  },

  DRAFT_UI: {
    pickProgress: (filled: number, total: number) =>
      `Escolha ${Math.min(filled + 1, total)} de ${total}`,
    roundLabel: (n: number) => `Lineup ${n}`,
    reroll: "Reroll",
    rerollsLeft: (n: number) => (n === 1 ? "1 restante" : `${n} restantes`),
    noRerolls: "Sem rerolls",
    freeReroll: "Reroll grátis",
    freeRerollHint: "Nada aqui serve para suas vagas restantes — esse é por nossa conta.",
    selectHint: "Toque numa carta para draftar — ela vai para a primeira vaga livre",
    yourRoster: "Seu Time",
    slotPlayer: (n: number) => `Jogador ${n}`,
    slotCoach: "Técnico",
    slotSub: "Reserva",
    slotOrg: "Org",
    empty: "Vazio",
    slotFull: "Vagas cheias",
    alreadyDrafted: "Já draftado",
    stillNeeded: "Ainda falta",
    hiddenOverall: "??",
    noCoach: "Sem Técnico",
    noSub: "Sem Reserva",
    notFielded: "Não atuou nesta season",
    player: "Jogador",
  },

  ONBOARDING: {
    howToTitle: "Como jogar",
    howToIntro: "Monte um elenco com a história da RLCS e dispute a chave. O básico:",
    howToSteps: [
      "A cada rodada sai uma lineup histórica da RLCS. Toque numa carta para draftá-la no seu time.",
      "Preencha 3 jogadores, um técnico, um reserva e uma org. A química é seu trunfo: junte mesmo país, org ou lineup histórica e um elenco coeso pode bater um time de estrelas com overall maior — o maior overall nem sempre é a escolha certa.",
      "Então um torneio joga sozinho: suíça e playoffs de dupla eliminação. Mais overall + química vence mais séries.",
      "Termine as runs — vencendo ou perdendo — para ganhar XP, subir de rank e desbloquear cartas especiais para sua coleção.",
    ],
    howToCta: "Bora draftar",
    legacyTitle: "Bem-vindo ao Legacy",
    legacyIntro: "Você desbloqueou o gauntlet histórico. Ele é diferente:",
    legacySteps: [
      "O campo está lotado dos maiores elencos campeões da história da RLCS.",
      "Os overalls ficam ocultos e não há rerolls — você drafta só no conhecimento.",
      "Vença aqui e você terá batido os melhores dos melhores. Boa sorte.",
    ],
    legacyCta: "Pode vir",
    regionalTitle: "Draft Regional",
    regionalIntro: "Esta run está travada na cena de uma região. Veja o que muda:",
    regionalSteps: [
      "O pool é só da região — seus times do Worlds MAIS o Top 8 regional que nunca chegou a um Mundial.",
      "Bancos mais profundos, heróis locais e zebras de culto que você nunca vê no draft mundial.",
      "O resto é igual: dificuldade, química, o torneio completo. Vença para erguer a bandeira da sua região.",
    ],
    regionalCta: "Bora jogar",
  },

  REVIEW: {
    title: "Revisão do Time",
    subtitle: "Conferida final antes do torneio. As escolhas estão travadas.",
    teamOverall: "Overall do Time",
    chemistry: "Química",
    orgBonus: "Bônus da Org",
    specialEffects: "Efeitos Especiais",
    noSpecials: "Nenhuma carta especial neste elenco.",
    breakdown: "Ligações de química",
    noChemistry: "Nenhuma ligação de química encontrada. Este elenco é um mix de all-stars puro.",
    readout: "Leitura do Analista",
    startTournament: "Começar Torneio",
    hiddenNote: "Os overalls ficam ocultos até a tela de resultados.",
    rowPlayers: "Jogadores (média)",
    rowCoach: "Técnico",
    rowSub: "Reserva",
    rowOrg: "Organização",
    rowChemistry: "Química",
    rowSpecials: "Especiais",
    statHigh: {
      offense: "Forte pressão ofensiva.",
      defense: "Difícil de furar.",
      mechanics: "Teto mecânico de elite.",
      consistency: "Base confiável, série após série.",
      experience: "Muita experiência de palco grande.",
      clutch: "Feito para jogos decisivos.",
    },
    statLow: {
      offense: "Pode ter dificuldade de criar chances.",
      defense: "Exposto na defesa às vezes.",
      mechanics: "Teto mecânico limitado.",
      consistency: "Sujeito a resultados voláteis.",
      experience: "Pouca experiência de palco grande.",
      clutch: "Não testado em jogos decisivos.",
    },
    chemistryLine: (tier: string) => `Química ${tier} entre as peças.`,
    orgBrings: (org: string, stat: string, level: string) =>
      `${org} traz ${stat} ${level} para o time.`,
    oneSpecial: "Um efeito de carta especial está ativo nesta run.",
    manySpecials: (n: number) => `${n} efeitos de cartas especiais estão ativos nesta run.`,
  },

  TUTORIAL: {
    kicker: "Bem-vindo",
    title: "Como o Rocket Draft funciona",
    skip: "Pular",
    next: "Próximo",
    back: "Voltar",
    done: "Bora jogar",
    steps: [
      {
        icon: "draft",
        title: "Drafte seu time",
        body: "A cada rodada aparece uma line da história da RLCS — escolha uma carta para um slot. Monte três jogadores, um técnico, um reserva e uma org.",
      },
      {
        icon: "field",
        title: "Depois, simule",
        body: "Seu time joga um campeonato completo — Suíço e depois playoffs. O overall dos jogadores mais a química decidem quem levanta a taça.",
      },
      {
        icon: "collection",
        title: "Monte uma Coleção",
        body: "As cartas especiais que você drafta ficam salvas para sempre na sua Coleção — momentos raros da história da RLCS para colecionar.",
      },
      {
        icon: "rank",
        title: "Ranks e recompensas",
        body: "Toda run dá XP. Subir de rank libera a Coleção, novas raridades de carta, o modo Difícil e mais chance de cartas especiais.",
      },
      {
        icon: "difficulty",
        title: "Escolha seu desafio",
        body: "O Normal dá pra ganhar com um bom time. O Difícil esconde os overalls e fortalece o chaveamento. O Legacy é um gauntlet histórico — só para campeões.",
      },
    ] as { icon: string; title: string; body: string }[],
  },

  TOURNAMENT_UI: {
    title: "Campeonato Estilo RLCS",
    swiss: "Fase Suíça",
    playoffs: "Playoffs",
    round: (n: number) => `Rodada ${n}`,
    record: (w: number, l: number) => `${w} – ${l}`,
    start: "Iniciar simulação",
    resume: "Retomar simulação",
    pause: "Pausar",
    speed: (x: number) => `${x}×`,
    skipAll: "Pular para o fim",
    live: "Ao vivo",
    standings: "Classificação",
    throughRound: (n: number) => `Até a Rodada ${n}`,
    yourPath: "Seu Caminho",
    matchCenter: "Central de Partidas",
    upcoming: "A seguir",
    bestOf: (n: number) => `Melhor de ${n}`,
    advanced: "Avançou",
    eliminated: "Eliminado",
    bracket: "Chave dos Playoffs",
    upperBracket: "Chave Superior",
    lowerBracket: "Chave Inferior",
    finals: "Finais",
    tbd: "A definir",
    toResults: "Ver resultados",
    reviewHint: "Clique em qualquer série finalizada para revê-la.",
    game: (n: number) => `Jogo ${n}`,
    overtime: "OT",
    matchPoint: "Match point",
    opponentHidden: "Os ratings do oponente ficam ocultos até a tela de resultados.",
    team: "Time",
    roundNames: {
      ub_quarterfinal: "Quartas (Sup)",
      lb_round1: "Inferior R1",
      ub_semifinal: "Semi (Sup)",
      lb_round2: "Inferior R2",
      ub_final: "Final (Sup)",
      lb_semifinal: "Semi (Inf)",
      lb_final: "Final (Inf)",
      third_place: "Terceiro Lugar",
      grand_final: "Grande Final",
      quarterfinal: "Quartas",
      semifinal: "Semifinal",
      final: "Final",
    },
  },

  RESULTS_UI: {
    title: "Run Completa",
    champion: "Campeões",
    championSub: "Seu elenco conquista o título.",
    runnerUp: "Vice-campeões",
    runnerUpSub: "A uma série do troféu.",
    third: "Terceiro Lugar",
    thirdSub: "No pódio após a decisão de bronze.",
    fourth: "Quarto Lugar",
    fourthSub: "Perdeu a decisão de bronze — ainda assim uma campanha longa.",
    top4: "Top 4",
    top4Sub: "A uma série da final.",
    top6: "Top 6",
    top6Sub: "A chave inferior encerrou a run.",
    top8: "Top 8",
    top8Sub: "Chegou aos playoffs, caiu no primeiro obstáculo.",
    swissExit: "Eliminado na Suíça",
    swissExitSub: "A chave fica fora de alcance desta vez.",
    swissRecord: "Campanha na suíça",
    finalPlacement: "Colocação final",
    champion0f: (name: string) => `${name} acabou levando o título.`,
    untouchableNote: "Nenhum gol sofrido na run inteira. Histórico.",
    untouchableBadge: "Intocável",
    teamOvrBadge: (n: number) => `OVR do time ${n}`,
    chemistryBadge: (tier: string) => `Química ${tier}`,
    teamReveal: "Revelação do Time",
    bestPlayer: "Melhor jogador",
    biggestWin: "Maior vitória",
    closestSeries: "Série mais apertada",
    worstLoss: "Derrota mais dura",
    ovr: (n: number) => `OVR ${n}`,
    unlocked: "Novas cartas desbloqueadas",
    unlockedNote: "adicionadas à sua coleção.",
    achievements: "Conquistas",
    achievementToast: "Conquista desbloqueada",
    xpGained: "XP ganho",
    difficultyMultiplier: "Multiplicador de dificuldade",
    hiddenOverallBonus: "Bônus de overall oculto",
    total: "Total",
    rankProgress: "Progresso de rank",
    rankUpBadge: "Subiu de rank!",
    xpToNext: (n: number, label: string) => `${n} XP para ${label}`,
    playAgain: "Jogar de novo",
    backHome: "Voltar ao menu",
    hiddenReveal: "Overalls revelados",
    share: "Compartilhar run",
    shareTitle: "Compartilhe sua run",
    shareNative: "Compartilhar",
    shareX: "Compartilhar no X",
    shareDownload: "Baixar",
    shareMsgChampion: "Fui campeão no Rocket Draft 🏆 — monte seu time dos sonhos da RLCS em",
    shareMsgPlacement: (placement: string) =>
      `Peguei ${placement} no Rocket Draft — monte seu time dos sonhos da RLCS em`,
    immaculateBadge: "Run impecável",
    ceremonyKicker: "Nova carta desbloqueada",
    ceremonyTap: "Toque em qualquer lugar para revelar",
    ceremonyContinue: "Continuar",
    ceremonyNext: "Próxima carta",
    rankUpKicker: "Subiu de rank",
    rankUpTitle: "Subiu de rank!",
    rankUpHint: "Toque em qualquer lugar para continuar",
    rankUpUnlocked: "Desbloqueado",
    unlockCollection: "A Coleção",
    unlockRarity: (label: string) => `Cartas especiais ${label}`,
    unlockHard: "Modo Difícil",
    unlockChance: (pct: number) => `${pct}% de chance de carta especial`,
    legacyKicker: "Novo modo desbloqueado",
    legacyTitle: "Legacy Desbloqueado",
    legacySub: "Um gauntlet histórico de elencos campeões agora espera por você.",
    legacyHint: "Toque em qualquer lugar para continuar",
    eliminatorKicker: "Quem encerrou sua run",
    eliminatedBy: (name: string) => `Eliminado por ${name}`,
    eliminatorScore: (a: number, b: number) => `${a}–${b}`,
    eliminatorBuffed: "Overall reforçado pela dificuldade (Legacy / região)",
  },

  COLLECTION_UI: {
    title: "Coleção",
    subtitle:
      "Cartas especiais são desbloqueadas ao draftá-las e terminar a run — vencendo ou perdendo.",
    progress: (n: number, total: number) => `${n}/${total} desbloqueadas`,
    filters: { all: "Todas", locked: "Bloqueadas", unlocked: "Desbloqueadas" },
    rarity: "Raridade",
    type: "Tipo",
    lockedCard: "Bloqueada",
    lockedHint: "Drafte esta carta e termine a run para desbloqueá-la.",
    unlockedOn: (date: string) => `Desbloqueada em ${date}`,
    lockedTitle: "Coleção bloqueada",
    lockedBody:
      "Chegue ao Bronze para abrir sua coleção — basta terminar uma run. As cartas especiais que você draftar ficam salvas aqui, e as raridades maiores são liberadas conforme você sobe de rank.",
    unlocksAt: (rank: string) => `Libera no ${rank}`,
    effect: "Efeito especial",
    context: "O momento",
    empty: "Nada aqui ainda. Termine runs com cartas especiais para crescer o álbum.",
  },

  SETTINGS_UI: {
    title: "Configurações",
    subtitle: "Ajuste a sensação do jogo. Salvo neste dispositivo.",
    soundSection: "Som",
    soundEnabled: "Efeitos sonoros",
    soundEnabledHint: "Sons sutis em drafts, revelações e resultados.",
    volume: "Volume",
    motionSection: "Movimento",
    reducedMotion: "Reduzir movimento",
    reducedMotionHint: "Minimiza animações (também segue a configuração do sistema).",
    animSpeed: "Velocidade das animações",
    animSpeedHint: "Quão rápido as revelações, o reel do draft e o torneio acontecem.",
    speedSlow: "Lenta",
    speedNormal: "Normal",
    speedFast: "Rápida",
    languageSection: "Idioma",
    language: "Idioma",
    reset: "Resetar configurações",
  },

  PROFILE_UI: {
    title: "Perfil",
    career: "Carreira",
    rank: "Rank",
    xp: "XP",
    toNext: (n: number) => `${n} XP para o próximo rank`,
    maxRank: "Rank máximo alcançado",
    runs: "Runs completas",
    titles: "Títulos",
    bestClear: "Melhor dificuldade vencida",
    specials: "Especiais coletadas",
    titleRate: "Taxa de títulos",
    playoffRate: "Taxa de playoffs",
    podiums: "Pódios",
    swissWins: "Vitórias na suíça",
    achievements: "Conquistas",
    viewAll: (n: number, total: number) => `${n}/${total} — ver todas`,
    history: "Histórico de runs",
    emptyHistory: "Nenhuma run ainda. Sua história começa no primeiro draft.",
    hidden: "Oculto",
    reset: "Resetar todo o progresso",
    resetConfirmTitle: "Resetar todo o progresso?",
    resetConfirmBody:
      "XP, rank, coleção, conquistas e histórico de runs serão apagados permanentemente neste dispositivo.",
    resetConfirm: "Apagar tudo",
    cancel: "Cancelar",
    none: "—",
    placement: {
      champion: "Campeão",
      runner_up: "Finalista",
      third: "3º Lugar",
      fourth: "4º Lugar",
      top4: "Top 4",
      top6: "Top 6",
      top8: "Top 8",
      swiss_exit: "Suíça",
      semifinalist: "Top 4",
      quarterfinalist: "Top 8",
    },
  },

  ACH_UI: {
    kicker: "Feitos para perseguir em cada run",
    title: "Conquistas",
    secretTitle: "???",
    secretHint: "Secreta — descubra jogando",
  },

  HOWTO: {
    kicker: "Regras do jogo",
    title: "Como Jogar",
    steps: [
      {
        title: "Drafte seu elenco",
        body: "A cada rodada aparece uma lineup histórica real da RLCS. Pegue exatamente uma carta — um jogador, o técnico, o reserva ou a organização. O pool de lineups é sempre totalmente aleatório, em toda dificuldade.",
      },
      {
        title: "Escolha livre, seis vagas",
        body: "Você precisa de 3 jogadores, 1 técnico, 1 reserva e 1 org. Escolha em qualquer ordem. Uma vez que uma pessoa está no seu elenco, as outras versões dela não podem ser draftadas de novo nesta run. Se nada numa lineup serve para suas vagas restantes, o reroll é grátis.",
      },
      {
        title: "Construa química",
        body: "A mesma lineup histórica é a ligação mais forte, o mesmo país é forte, a mesma organização também conta. Técnicos e reservas ligados aos seus jogadores somam um pouco mais. A química soma rating — mais nas dificuldades altas.",
      },
      {
        title: "Sobreviva à chave",
        body: "16 times. Fase suíça em melhor de 5: 3 vitórias para avançar, 3 derrotas e você está fora. O Top 8 entra numa chave de dupla eliminação em melhor de 7 — uma derrota na chave superior te joga para a inferior, não para fora do evento. O rating do seu time vem principalmente dos overalls dos jogadores — química, buffs de org, técnico e efeitos especiais dão a vantagem.",
      },
      {
        title: "Colecione cartas especiais",
        body: "Versões especiais raras das cartas podem aparecer em qualquer draft: momentos icônicos, campanhas de MVP, lendas. Drafte uma e termine a run — vencendo ou perdendo — e ela é desbloqueada na sua coleção para sempre.",
      },
    ],
    difficultiesTitle: "Dificuldades",
    unlockable: "Desbloqueável",
    reroll: (n: number) => `${n} reroll${n === 1 ? "" : "s"}`,
    ovrLockedHidden: "OVR travado oculto",
    ovrOptional: "OVR opcional",
    xpMult: (x: number) => `XP ×${x}`,
    raritiesTitle: "Raridades das cartas",
    raritySilver: "Prata",
    rarityGold: "Ouro",
    rarityBlue: "Azul",
    raritiesBefore: "Cartas base são ",
    raritiesMid1: " (79 ou menos), ",
    raritiesMid2: " (80–89) e ",
    raritiesAfter:
      " (90+). Com overalls ocultos, cartas base ficam pretas e mostram ?? — cartas especiais mantêm o visual, mas o número fica oculto até a tela de resultados.",
    startFirst: "Comece seu primeiro draft",
  },

  NARRATION: {
    seriesWin: [
      "Seu time fecha a série com folga.",
      "Série tranquila. A diferença apareceu no placar.",
      "Execução limpa do início ao fim.",
    ],
    seriesWinClose: [
      "Seu time sobrevive a uma série completa.",
      "Veio na menor das margens.",
      "Um jogo decisivo com tudo em jogo — e seu elenco entrega.",
    ],
    seriesLoss: [
      "Seu time não conseguiu fechar a série.",
      "O oponente ditou o ritmo o tempo todo.",
      "Uma série dura. O botão de reset existe por um motivo.",
    ],
    seriesLossClose: [
      "Um jogo de diferença. Essa vai doer.",
      "Um jogo decisivo escapa no fim.",
      "A centímetros da vitória — a série vai para o outro lado.",
    ],
    upsetWin: [
      "O elenco menos cotado encontra a zebra.",
      "Ninguém tinha essa no radar — seu time derruba o favorito.",
    ],
    upsetLoss: [
      "Zebra no placar — o favorito cai.",
      "Seu elenco é pego por um time jogando acima do rating.",
    ],
    overtimeNote: "A prorrogação decidiu.",
    clutchNote: "O fator clutch decidiu o jogo decisivo.",
    specialNote: "Um efeito de carta especial ativou.",
    starLine: (name: string) => `${name} liderou o ataque.`,
    starLineOpponent: (name: string) => `${name} estava em todo lugar pela oposição.`,
    chemistryNote: "A química fez a diferença num confronto apertado.",
    coachNote: "O bônus do técnico ajudou a estabilizar a run.",
  },

  STAT_LABELS: {
    offense: "Ataque",
    defense: "Defesa",
    mechanics: "Mecânica",
    consistency: "Consistência",
    experience: "Experiência",
    clutch: "Clutch",
  },

  SPECIAL_TYPE_LABELS: {
    moment: "Momento",
    major_mvp: "MVP de Major",
    worlds_mvp: "MVP do Mundial",
    season_mvp: "MVP da Temporada",
    mythic: "Mítica",
    legend: "Lenda",
    coach: "Técnico",
    masked: "Especial",
  },

  RARITY_LABELS: {
    common: "Comum",
    silver: "Prata",
    gold: "Ouro",
    blue: "Azul",
    rare: "Rara",
    epic: "Épica",
    mythic: "Mítica",
    legendary: "Lendária",
    creator: "Criador",
  },

  EFFECT_LABELS: {
    clutch_boost: "Clutch (jogos decisivos)",
    swiss_consistency: "Consistência (fase suíça)",
    playoff_experience: "Experiência (playoffs)",
    upset_boost: "Fator zebra (vs times mais cotados)",
    defense_stability: "Estabilidade defensiva",
    high_roll: "Teto mecânico",
  },

  CHEM_TIERS: {
    Poor: "Fraca",
    Okay: "Ok",
    Good: "Boa",
    Great: "Ótima",
    Perfect: "Perfeita",
  },

  PRIVACY: {
    kicker: "Aviso legal",
    title: "Política de Privacidade",
    sections: [
      {
        title: "Resumo rápido",
        body: [
          "Rocket Draft é um jogo gratuito, fan-made. Não exige conta e não vende nem compartilha seus dados pessoais. Seu progresso fica salvo no seu próprio dispositivo.",
        ],
      },
      {
        title: "O que fica salvo no seu dispositivo",
        body: [
          "Seu XP, rank, coleção, conquistas, histórico de runs, resultados dos desafios diários e configurações ficam salvos no armazenamento local do navegador. Esses dados nunca saem do seu dispositivo, a não ser que você os exporte.",
          "Limpar os dados do navegador, ou jogar em outro navegador ou no modo anônimo, vai zerar esse progresso.",
        ],
      },
      {
        title: "Analytics",
        body: [
          "Usamos analytics agregado e respeitoso à privacidade para entender quantas pessoas visitam o site, quais páginas são populares, como o jogo se comporta e como as runs acontecem — por exemplo, quais dificuldades as pessoas escolhem e com que frequência as runs são concluídas. Medimos isso com o Vercel Web Analytics e o PostHog, configurados para serem sem cookies e anônimos: não usamos cookies de publicidade, não identificamos você pessoalmente e respeitamos a opção Não rastrear (Do Not Track) do seu navegador.",
          "As estatísticas de busca (com que frequência o site aparece nos resultados) vêm do Google Search Console, que só reporta dados agregados e anônimos.",
        ],
      },
      {
        title: "Contas (em breve)",
        body: [
          "Uma atualização futura vai adicionar login opcional via Discord para sincronizar seu progresso entre dispositivos e habilitar rankings. Será totalmente opcional; até você escolher entrar, nada é enviado a um servidor. Quando isso chegar, esta política será atualizada para descrever exatamente o que é armazenado.",
        ],
      },
      {
        title: "Links de terceiros",
        body: [
          "O site tem links para serviços externos (Discord, X, uma página de apoio). Esses serviços têm as próprias políticas de privacidade, que valem a partir do momento em que você sai daqui.",
        ],
      },
      {
        title: "Sem afiliação",
        body: [
          "Rocket Draft é um projeto de fã, não oficial e sem fins lucrativos. Não é afiliado à Psyonix, Epic Games ou qualquer organização de esports. Rocket League é marca registrada de seus respectivos donos.",
        ],
      },
    ],
    contactBefore: "Dúvidas? Fale com",
    contactBetween: "no",
  },

  CHANGELOG_PAGE: {
    kicker: "Notas de versão",
    title: "Changelog",
    latest: "Mais recente",
    releases: [
      {
        version: "1.3.5",
        name: "Proving Grounds",
        date: "2026",
        current: true,
        notes: [
          "Dificuldade Legacy reajustada — o muro definitivo: só um draft de elite levanta o troféu (mundial ~97, SAM perto do seu teto realista), e agora os melhores têm uma chance mais justa, enquanto os times mais fracos seguem igualmente desafiados.",
          "A química premia história em comum — ex-companheiros, ou jogadores que passaram pela mesma org, criam link mesmo com cartas de times diferentes (e mesmo país sempre conta).",
          "O reserva importa mais: um sub forte é profundidade de elenco de verdade, e reservas agora podem aparecer como cartas especiais.",
          "A carta do Creator eleva o overall do time inteiro, além do bônus de atributos.",
          "A tela de resultados mostra o detalhamento do overall em todos os modos, e \"quem encerrou sua run\" revela o overall reforçado do time mais as cartas especiais que ele usou.",
          "Polimento da imagem de compartilhamento — cartas especiais mostram holo e borda de raridade, e toda carta exibe o escudo da org.",
          "Um endgame mais longo — a escada de XP se estende rumo ao Supersonic Legend, enquanto a Coleção continua liberando cedo no Bronze.",
        ],
      },
      {
        version: "1.3.0",
        name: "Season Rewards",
        date: "2026",
        current: false,
        notes: [
          "Progressão Season Rewards: seu rank agora desbloqueia conteúdo — raridades de cartas especiais, a Coleção e mais chance de cartas especiais conforme você sobe do Bronze ao Supersonic Legend.",
          "Nova química — monte seu time por nacionalidade e organização. Três jogadores do mesmo país chegam a Great; compartilhe uma org para Perfect.",
          "Modo Legacy rebalanceado — o gauntlet histórico continua brutal, mas o título finalmente é possível com um draft excelente e coeso.",
          "Chaveamentos com orgs únicas — você não enfrenta mais temporadas diferentes da mesma org no mesmo bracket.",
          "Simulação repaginada: vitórias e derrotas separadas em colunas, a rodada inteira do playoff revelada de uma vez, e cartas especiais sempre mostrando a arte.",
          "Tutorial na primeira vez, card de compartilhar sua run nas redes, e o detalhamento do overall do time agora na tela de resultados.",
          "Revisão de overalls da comunidade (69 overalls atualizados), novos times SAM e cartas especiais, e um novo achievement lendário.",
        ],
      },
      {
        version: "1.2.2",
        name: "",
        date: "2026",
        notes: [
          "As cartas de org ficaram mais fáceis de ler — em vez de pontinhos e sinais de mais enigmáticos, agora elas dizem direto: \"+2 Mechanics\" para um bônus, ou \"No buff\" quando não tem. As cartas de técnico seguem o mesmo padrão.",
          "Ajustes de elenco: adicionados alguns técnicos que faltavam (Team Liquid, mousesports, Evil Geniuses, Canberra Havoc) e corrigidos alguns nomes.",
        ],
      },
      {
        version: "1.2.1",
        name: "",
        date: "2026",
        current: false,
        notes: [
          "O Desafio Diário de hoje é especial — \"Loaded Draft\": duas cartas especiais garantidas para aparecer no seu draft, contra um campo mais forte. Aproveite o poder de fogo.",
          "As cartas especiais agora mostram o buff de cara — uma tag tipo \"+5 MEC\" na própria carta. Em runs com overall oculto, ela aparece como \"+?? MEC\".",
          "As conquistas ficaram mais coloridas — a estante de troféus agora é variada, em vez de um único tom por tier. As conquistas Legend mantêm o visual prismático característico.",
          "As cartas ficam melhores no celular: depois dos logos maiores, as cartas do draft e do team reveal não cortam mais nenhuma informação no mobile.",
          "Ficou mais fácil chegar na química Perfeita — um elenco que aposta em um país, org ou lineup compartilhada agora é recompensado no tier máximo.",
          "A carta Creator finalmente mostra seu brilho em campo, como toda carta especial.",
          "Polimento na tela de resultados: as cartas de técnico, reserva e org agora ficam alinhadas embaixo dos seus três jogadores.",
          "Textos mais afiados pelo site para as pessoas certas encontrarem o jogo.",
        ],
      },
      {
        version: "1.2.0",
        name: "Regional Champions",
        date: "2026",
        current: false,
        notes: [
          "Novo: Draft por Região. Escolha uma região na tela de setup e drafte da cena inteira dela — os times do Worlds MAIS o Top 8 regional que nunca chegou a um Mundial. A América do Sul (SAM) já está disponível; mais regiões em breve.",
          "Um pool sul-americano muito mais profundo — dezenas de novos times e jogadores da SAM pesquisados na Liquipedia.",
          "Os overalls de jogadores e técnicos do jogo inteiro passaram por uma revisão e ajuste manual.",
          "Uma nova conquista por vencer uma run regional — e uma carta secreta por aí para os curiosos.",
          "Corrigido: ao voltar do Hard para o Normal ou Easy, os overalls voltam a aparecer automaticamente.",
          "Os tutoriais ganharam um visual novo, e os momentos de subir de rank, nova carta e desbloqueio do Legacy agora são em tela cheia e esperam por você — só avançam quando você avança.",
          "Agora todo time exibe seu logo real, incluindo as novas orgs sul-americanas — e clubes históricos como NRG, Dignitas, Spacestation e Vitality mostram o logo correspondente a cada temporada.",
          "Nos bastidores: carregamento mais rápido e correções de indexação no Google.",
        ],
      },
      {
        version: "1.1.1",
        name: "",
        date: "2026",
        current: false,
        notes: [
          "Mais cartas especiais para colecionar — 80+ jogadores lendários, momentos de MVP e técnicos.",
          "A coleção fica melhor no celular: duas cartas por linha em vez de uma carta gigante.",
          "Tutoriais de primeira vez mais claros — cada dica agora é um card.",
          "Política de Privacidade e Changelog agora disponíveis em português.",
          "Base para insights de desempenho e uso que vão guiar as próximas versões.",
        ],
      },
      {
        version: "1.0.0",
        name: "Kickoff",
        date: "2026",
        current: false,
        notes: [
          "Lançamento público em rocketdraft.app.",
          "Tradução completa para português (PT-BR) com seletor de idioma.",
          "Configurações: volume, redução de movimento, velocidade das animações e idioma.",
          "Efeitos sonoros sutis durante o draft e o torneio.",
          "Desafios diários mais ricos, com seed fixa e número do dia.",
          "Polimento das cartas: overalls coloridos por raridade, cartas especiais holográficas em campo, layouts mais nítidos.",
          "Exporte / importe seu progresso para nunca perdê-lo.",
        ],
      },
      {
        version: "0.6.x",
        name: "Main Stage",
        date: "2026",
        current: false,
        notes: [
          "Raridades de cartas especiais repaginadas (lendária branco-dourada, mítica vermelha, épica, rara) com efeitos que escalam por tier.",
          "Comemorações de rank-up e de desbloqueio de cartas; a primeira vitória no Difícil libera o gauntlet Legacy.",
          "Jogo mais fluido no celular e reset de run com um toque.",
        ],
      },
      {
        version: "0.5.x",
        name: "",
        date: "2026",
        current: false,
        notes: [
          "Primeira rodada de playtest ao vivo: revisão geral de balance e um playback de torneio mais legível.",
          "Cartas especiais pertencem ao jogador; revelação da lineup estilo caça-níquel no draft.",
        ],
      },
      {
        version: "0.4.0",
        name: "",
        date: "2026",
        current: false,
        notes: ["Dataset completo das finais de RLCS — 208 lineups, 624 cartas, 2016–2026."],
      },
      {
        version: "0.1.0 – 0.3.0",
        name: "",
        date: "2025–2026",
        current: false,
        notes: [
          "Draft principal, torneio Suíço + dupla eliminação, coleção, conquistas e progressão.",
          "Modos Draft Rápido e Desafio Diário.",
        ],
      },
    ],
  },
};
