/**
 * Road to Worlds — copy PT-BR (modo carreira).
 *
 * Espelho exato de copy.career.en.ts (paridade de chaves garantida pelo tipo).
 * Tom: bancada de transmissão / análise pós-jogo. Termos canônicos da cena
 * (Split, Major, Worlds, OVR, Swiss) ficam em inglês.
 */

import type { CareerCopy } from "./copy.career.en";

export const CAREER_PT: CareerCopy = {
  meta: {
    title: "Road to Worlds",
    subtitle: "Construa uma org do zero. Vença o Mundial.",
    homeCardDesc:
      "Modo carreira: funde sua org, contrate e desenvolva jogadores, administre o orçamento e leve o calendário da RLCS até o Worlds.",
    nav: "Carreira",
    locked: "Disponível em breve",
    newBadge: "NOVO",
  },

  nav: {
    hub: "QG",
    calendar: "Calendário",
    squad: "Elenco",
    training: "Treinos",
    market: "Mercado",
    finances: "Finanças",
    standings: "Classificação",
    news: "Caixa de entrada",
    club: "Clube",
    more: "Mais",
    exit: "Voltar ao menu",
    saves: "Carreiras",
  },

  // Relógio por dia (v0.2) — renderização de datas (semanas começam na segunda).
  dates: {
    months: ["Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
    weekdays: ["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"],
    weekdaysLong: [
      "Segunda-feira",
      "Terça-feira",
      "Quarta-feira",
      "Quinta-feira",
      "Sexta-feira",
      "Sábado",
      "Domingo",
    ],
    short: (dow: string, month: string, d: number) => `${dow}, ${d} ${month}`,
    tiny: (month: string, d: number) => `${d} ${month}`,
    today: "Hoje",
    tomorrow: "Amanhã",
    inDays: (n: number) => `em ${n} dias`,
    daysShort: (n: number) => `${n}d`,
  },

  wizard: {
    title: "Funde sua organização",
    step: (n: number, total: number) => `Etapa ${n} de ${total}`,
    quickStart: "Início rápido",
    quickStartHint: "Aleatoriza tudo — dá para re-tintar as cores depois.",
    identityTitle: "Identidade",
    identityKicker: "Toda dinastia começa com um nome na camisa.",
    orgName: "Nome da organização",
    orgNamePlaceholder: "ex.: Horizon Esports",
    orgNameTaken: "Esse nome pertence a uma org existente.",
    orgNameLength: "2-18 caracteres.",
    abbrev: "Tag",
    abbrevHint: "2-4 letras, aparece nas tabelas e no escudo.",
    managerName: "Nome do manager",
    managerNamePlaceholder: "Seu nome na bancada.",
    country: "País",
    crestTitle: "Escudo & cores",
    crestKicker: "Escolha um símbolo. A cena vai aprender a respeitá-lo.",
    crestLabel: "Formato",
    crestSymbol: "Símbolo",
    crestPattern: "Padrão",
    crestNone: "Nenhum",
    randomizeCrest: "Aleatorizar",
    primaryColor: "Cor primária",
    secondaryColor: "Detalhe",
    identityBuff: "Identidade da org",
    identityBuffHint: "A especialidade da sua org — uma pequena vantagem coletiva.",
    regionTitle: "Região-sede",
    regionKicker: "Onde você joga define quem enfrenta — e quantas vagas de Worlds existem.",
    regionStrength: "Força do campo",
    regionSlots: (n: number) => `${n} vagas no Worlds`,
    regionRivals: "Rivais de peso",
    regionNote: "Mudar de região é desbloqueado mais adiante na carreira.",
    strengthDeep: "Campo profundo — o caminho difícil",
    strengthStrong: "Campo forte",
    strengthDeveloping: "Campo em formação — um caminho mais suave",
    rosterTitle: "Primeiras contratações",
    rosterKicker: "Três jogadores sem org. Um deles diz sim para a sua.",
    rosterProspects: "Promessas",
    rosterProspectsDesc: "Adolescentes com teto altíssimo. Exige paciência.",
    rosterJourneymen: "Rodados",
    rosterJourneymenDesc: "Os veteranos da cena. Prontos agora, sem margem de evolução.",
    rosterBalanced: "Equilibrado",
    rosterBalancedDesc: "Um pouco de agora, um pouco de depois.",
    recommended: "Recomendado",
    wageBill: "Folha salarial",
    avgAge: "Idade média",
    avgOverall: "OVR médio",
    finalTitle: "Última chamada",
    finalKicker: "A dificuldade molda adversários e pressão financeira — nunca quem você pode contratar.",
    styleTitle: "Estilo de gestão",
    styleHandsOn: "Mão na massa",
    styleHandsOnDesc: "Você define cada foco, cada proposta, cada escalação.",
    styleBalanced: "Equilibrado",
    styleBalancedDesc: "Padrões inteligentes, recomendações em destaque. Você confirma.",
    styleDelegate: "Delegar",
    styleDelegateDesc: "O coach cuida da rotina — tudo reportado, assuma quando quiser.",
    summaryTitle: "A papelada",
    found: (org: string) => `Fundar ${org}`,
    founded: "EST. 2020",
    foundedSplash: "Um novo nome entra na cena.",
  },

  hub: {
    title: "QG",
    continue: "Continuar",
    continueTo: (label: string) => `Avançar — ${label}`,
    advanceDay: "Avançar um dia",
    nowNext: "A seguir",
    nowDecision: "Decisão pendente",
    week: (n: number) => `Semana ${n}`,
    matchdayIn: (n: number) => (n === 0 ? "DIA DE JOGO" : n === 1 ? "Jogo amanhã" : `Jogo em ${n} dias`),
    seasonGoal: "Meta da temporada",
    goalStretch: "Meta ousada",
    rosterForm: "Elenco",
    form: "Fase",
    chemistry: "Química",
    pointsRace: "Road to Worlds",
    pointsRank: (rank: number, pts: number) => `#${rank} · ${pts} pts`,
    pointsGap: (pts: number) => `${pts} pts abaixo da linha`,
    pointsSafe: "Acima da linha de corte",
    budget: "Saldo",
    budgetNet: (s: string) => `${s} / split`,
    budgetWarning: "Projeção negativa até o próximo pagamento",
    news: "O plantão",
    newsAll: "Feed completo",
    inboxTeaser: "Caixa de entrada",
    inboxAll: "Abrir caixa de entrada",
    sponsor: "Meta do patrocinador",
    trainingWeek: "Semana de treino — o elenco ganha reps extras",
    thisWeek: "Esta semana",
    comingUp: "Vem por aí",
    quickActions: "Hoje no escritório",
    scrimCta: (opp: string) => `Scrim vs ${opp}`,
    scrimsLeft: (n: number) => (n === 1 ? "1 bloco de scrim restante na semana" : `${n} blocos de scrim restantes na semana`),
    scrimUnavailable: "Sem bloco de scrim disponível hoje",
    restDay: "Dia de descanso — o elenco recarrega",
    progression: "Próximo desbloqueio",
    emptyStateTitle: "Bem-vindo à bancada",
    emptyStateBody: "Seu primeiro torneio já está no calendário. Aperte Continuar quando estiver pronto.",
  },

  // Caixa de entrada v0.2 — correio endereçado ao manager.
  mail: {
    title: "Caixa de entrada",
    unread: (n: number) => `${n} não lidas`,
    markAllRead: "Marcar tudo como lido",
    empty: "Nenhum e-mail. A mesa está quieta — por enquanto.",
    emptyHint: "Propostas de transferência, patrocínios e avisos de contrato chegam aqui.",
    open: "Abrir",
    from: {
      board: "A Diretoria",
      agent: "Agentes de jogadores",
      sponsor: "Relações com patrocinadores",
      backer: "Investidor de emergência",
      league: "Operações da liga",
      staff: "Operações do time",
    },
    kinds: {
      offer: "Transferência",
      sponsor: "Patrocínio",
      contract: "Contratos",
      finance: "Finanças",
      unlock: "Desbloqueado",
      club: "Clube",
    },
    tpl: {
      incomingBid: (p: Record<string, string | number>) => `Proposta por ${p.player}`,
      blockbusterBid: (p: Record<string, string | number>) => `BOMBA: ${p.org} querem ${p.player}`,
      sponsorOffers: () => `Propostas de patrocínio na sua mesa`,
      objectiveHit: (p: Record<string, string | number>) => `${p.name}: meta entregue`,
      objectiveMissed: (p: Record<string, string | number>) => `${p.name}: meta perdida`,
      contractExpiring: (p: Record<string, string | number>) => `${p.player} — contrato na última temporada`,
      backerIn: () => `Aporte de emergência garantido`,
      unlock: (p: Record<string, string | number>) => `Novidade para a org: ${p.name}`,
    },
    body: {
      incomingBid: (p: Record<string, string | number>) =>
        `${p.org} formalizaram uma proposta de ${p.fee} por ${p.player}. Ela expira quando a janela fechar — aceite ou recuse na aba de negociações do Mercado.`,
      blockbusterBid: (p: Record<string, string | number>) =>
        `${p.org} vieram com tudo: ${p.fee} por ${p.player}. Recusar uma proposta desse tamanho pode inflar a próxima renovação dele — mas ninguém vende o próprio core de graça.`,
      sponsorOffers: () =>
        `Marcas estão de olho na org. Avalie as propostas em Finanças — a base é garantida; o bônus depende da meta.`,
      objectiveHit: (p: Record<string, string | number>) =>
        `A meta do split foi entregue. O bônus de ${p.bonus} cai junto com o pagamento. Bom negócio.`,
      objectiveMissed: (p: Record<string, string | number>) =>
        `A meta do split escapou. Ninguém cobra dinheiro de volta — mas faltas repetidas derrubam o tier da renovação. (Faltas até aqui: ${p.misses}.)`,
      contractExpiring: (p: Record<string, string | number>) =>
        `${p.player} está na última temporada de contrato. Você tem janela exclusiva de renovação até o fim do Split 3 — depois disso, ele sai de graça.`,
      backerIn: () =>
        `As contas romperam o piso e o Investidor de emergência entrou — uma única vez. O pagamento sai descontado da premiação. Um segundo colapso encerra a org.`,
      unlock: (p: Record<string, string | number>) =>
        `O progresso da org desbloqueou: ${p.name}. Confira a trilha de progressão no Clube — o arsenal cresce com a reputação.`,
    },
  },

  // Scrims v0.2 — blocos de dia útil entre eventos.
  scrim: {
    title: "Bloco de scrim",
    desc: "Uma MD5 de portas fechadas: reps de química e desenvolvimento leve. Dois blocos por semana.",
    vs: (opp: string) => `vs ${opp}`,
    run: "Rodar scrim",
    won: (opp: string, a: number, b: number) => `Scrim V ${a}-${b} vs ${opp}`,
    lost: (opp: string, a: number, b: number) => `Scrim D ${a}-${b} vs ${opp}`,
    usedUp: "Sem blocos de scrim restantes nesta semana",
    restDay: "Nada de scrim em dia de descanso",
  },

  calendar: {
    title: "Calendário",
    thisWeek: "Esta semana",
    today: "Hoje",
    preseason: "Pré-temporada",
    openWeek: "Semana livre",
    window: "Janela de transferências",
    worldsWindow: "Janela do Worlds",
    windowOpen: "Janela aberta",
    windowCloses: (n: number) =>
      n <= 0 ? "A janela fecha hoje" : n === 1 ? "A janela fecha amanhã" : `A janela fecha em ${n} dias`,
    regional: (n: number) => `Regional ${n}`,
    major: "Major",
    worlds: "Mundial",
    split: (n: number) => `Split ${n}`,
    registered: "Inscrito",
    notQualified: "Não classificado",
    spectate: "Ver resultados",
    done: "Encerrado",
    stakes: "Em jogo",
    prizePool: "Premiação",
    points: "Pontos da Temporada",
    field: "Chave",
    fieldQuality: "Nível do campo",
    enter: "Entrar",
    skip: "Passar",
    skipHint: "Passar mantém a semana para treinos (+25% de eficiência).",
    offerTitle: "Convite de torneio",
    seasonOverview: "Visão da temporada",
    // Visão por dia (v0.2)
    monthView: "Mês",
    agendaView: "Agenda",
    nextForYou: "Próximos para você",
    matchday: "Dia de jogo",
    payday: "Pagamento",
    trainingDay: "Treino",
    restDay: "Descanso",
    scrimDay: "Scrim",
    legend: "Legenda",
    advanceDay: "Avançar um dia",
    advanceToStop: (label: string) => `Continuar — ${label}`,
    seasonEnd: "Fim da temporada",
    showWorld: "Mostrar outras regiões",
    hideWorld: "Só a minha agenda",
    worldEvents: "Pelo mundo",
  },

  squad: {
    title: "Elenco",
    starters: "Titulares",
    bench: "Banco",
    subSlot: "Substituto",
    coachSlot: "Coach",
    staffRow: "Staff & boosts",
    hire: "Contratar",
    emptySub: "Sem sub — uma ausência custa taxa de emergência e química.",
    emptyCoach: "Um coach acelera o desenvolvimento e a preparação.",
    contracts: "Contratos",
    wage: "Salário",
    perSplit: (s: string) => `${s} / split`,
    expires: (label: string) => `Termina ${label}`,
    expiring: "Contrato expirando",
    renew: "Renovar",
    release: "Dispensar",
    releaseFee: (s: string) => `Rescisão: ${s}`,
    releaseConfirm: (name: string) => `Dispensar ${name}?`,
    releaseBody: "A rescisão é paga agora; o salário sai da folha.",
    makeStarter: "Promover a titular",
    makeSub: "Mover para o banco",
    swapPreview: (a: number, b: number) => `Rating do time ${a} → ${b}`,
    chemPreview: (a: number, b: number) => `Química ${a}% → ${b}%`,
    bestLineup: "Melhor escalação",
    stability: "Estabilidade do elenco",
    stabilityState: (used: number, max: number) => `Caras novas neste split: ${used}/${max}`,
    stabilityWarning: (pct: number, pts: number) =>
      `Escalar mais uma cara nova custa ${pct}% dos seus ${pts} Pontos da Temporada`,
    finalSeason: "Última temporada",
    squadFull: "Elenco cheio (3 titulares + 1 sub)",
  },

  player: {
    age: (n: number) => `${n} anos`,
    potential: "Potencial",
    potBand: (min: number, max: number) => `POT ${min}-${max}`,
    potExact: (v: number) => `POT ${v}`,
    overall: "Overall",
    attributes: "Atributos",
    development: "Desenvolvimento",
    contract: "Contrato",
    history: "Histórico",
    scoutReport: "Relatório de olheiro",
    scoutCost: (s: string) => `Encomendar relatório · ${s}`,
    scoutDone: "Totalmente observado",
    scoutHint: "Estreita a faixa de potencial.",
    growthRoom: "Margem de evolução",
    phase: { growing: "Em evolução", prime: "Auge", declining: "Em declínio" },
    projected: (v: string) => `Projeção: ${v} até o fim do split`,
    trainingFocusLabel: "Foco de treino",
    archetype: {
      mechanical: "Mecânico",
      anchor: "Âncora",
      playmaker: "Armador",
      icecold: "Sangue Frio",
      veteranmind: "Mente Veterana",
      allround: "Completo",
    },
    archetypeHint: {
      mechanical: "Teto altíssimo, piso instável.",
      anchor: "Segura o segundo poste. Vence jogo feio.",
      playmaker: "Cria para todo mundo. Lê o campo primeiro.",
      icecold: "Quer o jogo decisivo.",
      veteranmind: "Mãos mais lentas, cérebro mais rápido.",
      allround: "Sem buracos no kit.",
    },
    fictionalTag: "Jogador da simulação",
  },

  training: {
    title: "Treinos",
    autoTrain: "Delegar ao coach",
    autoTrainDesc: "O coach define o foco de cada jogador e reporta os resultados.",
    handledByCoach: "Definido pelo coach",
    manageMyself: "Quero cuidar disso",
    focus: "Foco",
    balanced: "Equilibrado",
    auto: "Auto",
    coachEffect: (name: string, pct: number) => `Coach ${name}: ${pct > 0 ? "+" : ""}${pct}% de eficiência`,
    noCoach: "Sem coach — o desenvolvimento roda abaixo do ritmo.",
    facilityEffect: (pct: number) => `Equipamentos: +${pct}% de eficiência`,
    projection: (v: string) => `+${v} OVR neste split`,
    matchXpHint: "Jogar contra campos fortes desenvolve mais que qualquer treino.",
    report: (delta: string) => `Relatório de treinos: elenco ${delta} OVR`,
    // v0.2 — focos com identidade, intensidade, ritmo semanal
    weeklyPlan: "Plano semanal",
    weeklyPlanHint: "Sessões de segunda a sexta. Jogo no sábado. Domingo descansa.",
    perWeekOverall: (v: string) => `+${v} OVR / semana`,
    perWeekOffset: (v: string, stat: string) => `+${v} ${stat} / semana`,
    focusHintBalanced: "Crescimento puro de overall — nada afiado.",
    focusHintAttr: "Troca uma fatia do crescimento de overall para afiar um atributo.",
    focusHintAuto: "O coach escolhe a ênfase da semana — quase ótimo, sem esforço.",
    intensity: "Intensidade",
    intensityLight: "Leve",
    intensityNormal: "Normal",
    intensityHeavy: "Pesada",
    intensityLightHint: "-40% de desenvolvimento, zero risco de fadiga.",
    intensityNormalHint: "O bloco padrão.",
    intensityHeavyHint: "+35% de desenvolvimento — adiciona um pequeno risco (avisado) de ausência antes de eventos.",
    fatigueWarning: "Sessões pesadas aumentam o risco de ausência pré-evento",
    sessionToday: "Sessão de hoje",
    noSessionToday: "Sem sessão hoje",
    matchPrepWeek: "Semana de jogo — sessões pausam; o evento paga XP de partida",
  },

  market: {
    title: "Mercado",
    freeAgents: "Agentes livres",
    contracted: "Sob contrato",
    myDeals: "Minhas negociações",
    windowClosed: "Mercado fechado",
    windowClosedHint: (label: string) => `A janela de transferências abre ${label}`,
    scoutingOpen: "A observação segue aberta entre janelas.",
    fee: "Taxa de transferência",
    signingBonus: "Luvas",
    freeAgentTag: "Agente livre",
    ask: "Pedida",
    whyPrice: "Por que esse preço",
    factor: {
      overall: "Rating",
      age: "Idade",
      potential: "Potencial",
      repPremium: "Prêmio de estrela",
      length: "Duração do contrato",
      contract: "Sob contrato",
    },
    lengthLabel: "Duração do contrato",
    seasons: (n: number) => (n === 1 ? "1 temporada" : `${n} temporadas`),
    roleLabel: "Função",
    starter: "Titular",
    sub: "Substituto",
    signCta: "Contratar",
    offerSent: "Negócio registrado — resolve no próximo avanço.",
    signed: (name: string) => `${name} assina com a org`,
    rejected: (name: string) => `${name} recusou os termos`,
    recommendedShelf: "Contratações recomendadas",
    recommendedWhy: (reason: string) => `Encaixe: ${reason}`,
    affordable: "Cabe no caixa",
    incomingBid: "Proposta recebida",
    bidFrom: (org: string) => `Proposta de ${org}`,
    accept: "Aceitar",
    decline: "Recusar",
    declineHint: "Recusar uma proposta grande pode aumentar a próxima pedida de renovação.",
    blockbuster: "Bombástica",
    consequences: "Depois deste negócio",
    balanceAfter: (s: string) => `Saldo após: ${s}`,
    wageAfter: (s: string) => `Folha após: ${s} / split`,
    squadFullWarning: "Elenco cheio — dispense ou venda antes.",
    shopHim: "Colocar na vitrine",
    shopHimHint: "Sinaliza disponibilidade — espere propostas na próxima janela.",
    quickFlipWarning: "Contratado há pouco — vende com deságio.",
    // v0.2 — mercado de coaches + ferramentas de busca
    coaches: "Coaches",
    coachRealTag: "Ex-pro",
    coachGenTag: "Coach",
    coachBonus: (stat: string) => `Reforça ${stat}`,
    hireCoach: "Contratar",
    currentCoach: "Coach atual",
    replaceWarning: "Trocar de coach paga um split de rescisão.",
    searchPlaceholder: "Buscar jogadores…",
    sortBy: "Ordenar",
    sortOvr: "Overall",
    sortAge: "Idade",
    sortPrice: "Preço",
    sortPot: "Potencial",
    filterRegion: "Região",
    allRegions: "Todas as regiões",
    viewSheet: "Ver ficha",
    noResults: "Nenhum jogador com esses filtros.",
    dealsEmpty: "Nenhuma negociação ativa. Propostas chegam aqui com a janela aberta.",
    errors: {
      windowClosed: "A janela de transferências está fechada.",
      alreadySigned: "Já está no elenco.",
      squadFull: "Elenco cheio — dispense ou venda antes.",
      unavailable: "Jogador indisponível.",
      funds: "Caixa insuficiente para este negócio.",
      loanActive: "Sem transferências com taxa enquanto o empréstimo do investidor estiver ativo.",
      unknown: "Esse negócio não está mais disponível.",
      locked: "Bloqueado por enquanto.",
      maxed: "Já está no máximo.",
      used: "Já utilizado.",
      restDay: "Não em dia de descanso.",
      blocked: "Agora não.",
      none: "Nada a fazer.",
      invalid: "Seleção inválida.",
    },
  },

  finances: {
    title: "Finanças",
    balance: "Saldo",
    net: "Líquido / split",
    projected: "Projeção após o pagamento",
    income: "Entradas",
    expenses: "Saídas",
    ledger: "Movimentações",
    payday: "Dia de pagamento",
    ledgerKind: {
      prize: "Premiação",
      sponsorBase: "Pagamento de patrocínio",
      sponsorBonus: "Bônus de patrocínio",
      sponsorSigning: "Luvas do patrocínio",
      salary: "Salários dos jogadores",
      coachSalary: "Salário do coach",
      severance: "Rescisão",
      transferIn: "Taxa de transferência recebida",
      transferOut: "Taxa de transferência paga",
      signingBonus: "Luvas",
      releaseFee: "Taxa de dispensa",
      standInFee: "Substituto de emergência",
      facility: "Upgrade de instalações",
      upkeep: "Manutenção das instalações",
      buff: "Staff & boosts",
      loanGrant: "Resgate do investidor",
      loanGarnish: "Reembolso ao investidor",
      fanbase: "Receita de torcida",
    },
    sponsors: "Patrocinadores",
    sponsorTier: (t: number) => `Nível ${t}`,
    sponsorObjective: "Meta",
    objective: {
      enterEvents: (n: number) => `Dispute ${n}+ eventos neste split (oficiais contam)`,
      regionalTop8: "Alcance um top-8 regional neste split",
      majorQualify: "Classifique-se para o Major",
      majorTop4: "Alcance o top-4 do Major",
    },
    onTrack: "No caminho",
    objectiveHit: "Entregue",
    objectiveMissed: "Perdida neste split",
    patience: (n: number, max: number) => `Confiança do patrocinador: ${max - n} de ${max}`,
    patienceWarn: "Mais um tropeço e a oferta da próxima temporada cai um nível.",
    offerTitle: "Ofertas de patrocínio",
    perSplitBase: (s: string) => `${s} / split garantidos`,
    bonusFor: (s: string) => `+${s} por meta batida`,
    backer: "Investidor de emergência",
    backerRemaining: (s: string) => `Investidor: ${s} a reembolsar`,
    backerLine: (pct: number) => `Reembolsado da premiação (${pct}%)`,
    backerWarning: "Este negócio provavelmente aciona o investidor de emergência.",
    backerRescued: "O investidor entrou — um resgate por carreira. Quebrar de novo encerra a história.",
    insolvencyWarning: "As contas estão ruindo. Um segundo colapso encerra a carreira.",
    boosts: "Boosts & staff",
    psychologist: "Psicóloga esportiva",
    psychologistDesc: "+1 Clutch, +1 Consistência enquanto contratada. A contratação que vence jogos decisivos.",
    bootcamp: "Bootcamp",
    bootcampDesc: "Ganho permanente de química + próximo evento oficial mais afiado.",
    bootcampUsed: "Bootcamp já realizado neste split.",
    upkeepLabel: (s: string) => `Manutenção ${s} / split`,
    lockedAtRep: (rep: number) => `Desbloqueia com ${rep} de Reputação`,
    activeLabel: "Ativo",
    ownedLabel: "Adquirido",
    retainedLabel: "Contratada",
    hireLabel: "Contratar",
    dropLabel: "Encerrar contrato",
    buy: "Comprar",
    // Escada de equipamentos & staff (v0.2)
    gearLadder: "O arsenal da org",
    gearLadderHint: "Comprado em ordem, desbloqueado por reputação — uma org de garagem vira potência.",
    gear: {
      peripherals: "Periféricos pro",
      monitors: "Monitores 240Hz",
      pcs: "PCs de torneio",
      perfCenter: "Centro de Performance",
    },
    gearDesc: {
      peripherals: "Controles, mouses e teclados que os jogadores realmente pediram. +5% de treino.",
      monitors: "Chega de desculpa de frame. +5% de treino.",
      pcs: "Máquinas nível servidor de scrim. +10% de treino e uma vantagem real de rating.",
      perfCenter: "O prédio completo: sala de análise, academia, teatro de review. +15% de treino, vantagem de elite.",
    },
    bootcampT1: "Bootcamp",
    bootcampT1Desc: "Uma semana sob o mesmo teto. Ganho de química + leve vantagem no próximo oficial.",
    bootcampT2: "Bootcamp estruturado",
    bootcampT2Desc: "Comissão técnica, agenda de scrims, review de VOD. Mais química + próximo oficial afiado.",
    sponsorPerks: "Vantagens do patrocinador",
    perkDiscount: (pct: number) => `${pct}% de desconto em equipamentos`,
    perkBootcamps: (n: number) => (n === 1 ? "1 bootcamp grátis / temporada" : `${n} bootcamps grátis / temporada`),
    perkNone: "Sem vantagens neste nível",
    freeBootcampLeft: (n: number) =>
      n === 1 ? "1 bootcamp pago pelo patrocinador restante na temporada" : `${n} bootcamps pagos pelo patrocinador restantes na temporada`,
  },

  standings: {
    title: "Classificação",
    splitTab: "Classificação do split",
    seasonTab: "Road to Worlds",
    majorLine: "Linha do Major",
    worldsLine: "Linha do Worlds",
    clinched: "Classificado",
    contention: "Na briga",
    eliminated: "Fora da corrida",
    ptsShort: "pts",
    remaining: (n: number) => `${n} eventos restantes`,
    maxAvailable: (n: number) => `${n} pts ainda em disputa`,
    userChip: "Você",
    regionLabel: "Região",
    worldsField: "Chave do Worlds",
    fieldRevealPending: "Revelada quando todas as regiões concluírem",
  },

  news: {
    title: "Central",
    unread: (n: number) => `${n} não lidas`,
    markAllRead: "Marcar tudo como lido",
    filter: { all: "Tudo", mine: "Minha org", region: "Minha região", world: "Mundo", deals: "Negócios" },
    wire: "PLANTÃO",
    digest: (n: number) => `Giro pela liga: mais ${n} movimentações`,
    tpl: {
      transfer: (p: Record<string, string | number>) => `${p.player} assina com ${p.to}`,
      transferFee: (p: Record<string, string | number>) => `${p.to} tira ${p.player} de ${p.from} (${p.fee})`,
      transferFa: (p: Record<string, string | number>) => `${p.player} encontra casa na ${p.to}`,
      userSigned: (p: Record<string, string | number>) => `Oficial: ${p.player} chega a ${p.org}`,
      userSold: (p: Record<string, string | number>) => `${p.player} deixa ${p.org} rumo à ${p.to}`,
      userReleased: (p: Record<string, string | number>) => `${p.org} dispensa ${p.player}`,
      result: (p: Record<string, string | number>) => `${p.org} levam o ${p.event}`,
      resultUser: (p: Record<string, string | number>) => `${p.event}: você termina em ${p.placement}`,
      qualifiedMajor: () => `Está dentro. O Major espera.`,
      missedMajor: () => `O Major acontece sem você neste split.`,
      qualifiedWorlds: () => `WORLDS. A org chegou lá.`,
      missedWorlds: () => `A corrida pelo Worlds termina aqui nesta temporada.`,
      stability: (p: Record<string, string | number>) => `Reformulação do elenco custa ${p.points} Pontos da Temporada`,
      contractExpiring: (p: Record<string, string | number>) => `O contrato de ${p.player} entra na janela final`,
      playerLeft: (p: Record<string, string | number>) => `${p.player} sai como agente livre`,
      retirementAnnounce: (p: Record<string, string | number>) => `${p.player} anuncia sua última temporada`,
      retired: (p: Record<string, string | number>) => `${p.player} pendura o controle`,
      rookieClass: (p: Record<string, string | number>) => `Chega a turma de novatos de ${p.region} — ${p.name} é o destaque`,
      decline: (p: Record<string, string | number>) => `${p.player}, ${p.n}, perdeu meio passo`,
      breakout: (p: Record<string, string | number>) => `${p.player} está superando todas as projeções`,
      trainingReport: (p: Record<string, string | number>) => `Relatório de treinos: elenco ${p.n} OVR`,
      windowOpen: () => `Janela de transferências aberta — os telefones ligados`,
      windowClose: () => `Janela fechada. Os elencos são o que são.`,
      sponsorSigned: (p: Record<string, string | number>) => `${p.org} anuncia parceria com ${p.name}`,
      sponsorDropped: (p: Record<string, string | number>) => `${p.name} esfria a parceria`,
      repUp: (p: Record<string, string | number>) => `A cena está falando de ${p.org}`,
      repDown: (p: Record<string, string | number>) => `Analistas pegam pesado após o tropeço de ${p.org}`,
      starUp: (p: Record<string, string | number>) => `${p.org} alcança o status de ${p.n} estrelas`,
      unlock: (p: Record<string, string | number>) => `Desbloqueado: ${p.name}`,
      unavailable: (p: Record<string, string | number>) => `${p.player} está fora de ${p.event}`,
      standIn: (p: Record<string, string | number>) => `Substituto de emergência entra em ${p.event}`,
      backerIn: () => `Um investidor de emergência estabiliza as contas`,
      insolvency: () => `As finanças da org entram em colapso`,
      seasonChampion: (p: Record<string, string | number>) => `${p.org} são os campeões do ${p.event}`,
      gearBought: (p: Record<string, string | number>) => `Upgrade na org: ${p.name} instalado`,
      bootcampRun: (p: Record<string, string | number>) =>
        Number(p.tier) >= 2 ? `Bootcamp estruturado concluído` : `Semana de bootcamp concluída`,
      coachHired: (p: Record<string, string | number>) => `${p.org} traz ${p.coach}`,
      scrimWin: (p: Record<string, string | number>) => `Portas fechadas: scrim V ${p.a}-${p.b} vs ${p.opponent}`,
      scrimLoss: (p: Record<string, string | number>) => `Portas fechadas: scrim D ${p.a}-${p.b} vs ${p.opponent}`,
      blockbusterBid: (p: Record<string, string | number>) => `${p.org} fazem proposta bombástica por ${p.player}`,
      flavor1: () => `Notas da bancada: disciplina de rotação é o novo jargão do meta`,
      flavor2: () => `Servidores de scrim lotados — a região inteira está no grind`,
      flavor3: () => `O microfone de um caster pegou uma análise bem sincera no intervalo`,
      flavor4: () => `Reclamações de ping registradas. Reclamações de ping arquivadas.`,
      flavor5: () => `Uma montage da comunidade está bombando esta semana`,
    },
    // v0.2 — corpo de texto por template (mesmos params; o feed do QG renderiza).
    body: {
      transferFee: (p: Record<string, string | number>) =>
        `${p.to} acertou a taxa com ${p.from} por ${p.player}. O mapa da região se redesenha de novo.`,
      transferFa: (p: Record<string, string | number>) =>
        `${p.player} estava sem org — ${p.to} chegou primeiro. Valor de agente livre, se o encaixe funcionar.`,
      userSigned: (p: Record<string, string | number>) =>
        `Papelada assinada: ${p.player} é seu. A química começa do zero — a tabela só lembra de resultados.`,
      userSold: (p: Record<string, string | number>) =>
        `${p.player} sai rumo à ${p.to}. A taxa entra no caixa; o buraco na escalação é problema seu.`,
      userReleased: (p: Record<string, string | number>) =>
        `${p.org} pagou a rescisão e seguiu em frente. ${p.player} entra no mercado de agentes livres.`,
      result: (p: Record<string, string | number>) =>
        `${p.org} fecharam o ${p.event}. A bancada vai reprisar essa grande final por semanas.`,
      resultUser: (p: Record<string, string | number>) =>
        `A campanha da org no ${p.event} termina em ${p.placement}. Toda colocação paga — e a tabela lembra.`,
      qualifiedMajor: () =>
        `A classificação do split travou e o seu nome está acima da linha. Chave inter-regional, pontos em dobro — o teste de verdade.`,
      missedMajor: () =>
        `Abaixo da linha quando ela travou. O próximo split zera a corrida — os pontos de Worlds já garantidos continuam valendo.`,
      qualifiedWorlds: () =>
        `Uma temporada inteira de pontos garantiu. A maior chave do jogo espera — um bracket para tudo.`,
      missedWorlds: () =>
        `Os pontos da temporada não bastaram. A org assiste ao Worlds de casa — e planeja a volta.`,
      stability: (p: Record<string, string | number>) =>
        `Escalar mais uma cara nova no meio do split custou ${p.points} Pontos da Temporada. Reformulação é coisa de pré-temporada.`,
      contractExpiring: (p: Record<string, string | number>) =>
        `O contrato de ${p.player} está acabando. Você tem janela exclusiva de renovação até o fim do Split 3.`,
      playerLeft: (p: Record<string, string | number>) =>
        `A renovação não veio e ${p.player} saiu de graça. Agentes conversam — a próxima negociação começa daí.`,
      retirementAnnounce: (p: Record<string, string | number>) =>
        `${p.player} vai se aposentar no fim da temporada. Uma última campanha juntos — faça valer.`,
      retired: (p: Record<string, string | number>) =>
        `${p.player} deixa o jogo. A cena fica mais jovem — e um pouco mais pobre — hoje.`,
      rookieClass: (p: Record<string, string | number>) =>
        `Nomes novos chegam ao mercado de ${p.region}. ${p.name} é o que os olheiros sublinham.`,
      decline: (p: Record<string, string | number>) =>
        `A idade cobra a mecânica primeiro. ${p.player} está adaptando o próprio jogo — a experiência segue pagando.`,
      windowOpen: () =>
        `Agentes atendendo, taxas circulando, elencos destravados. Negócios resolvem com o passar dos dias; a janela não espera.`,
      sponsorSigned: (p: Record<string, string | number>) =>
        `${p.org} e ${p.name} assinaram pela temporada. Base garantida, bônus na meta — entregue e o nível cresce.`,
      unlock: (p: Record<string, string | number>) =>
        `A reputação abriu uma porta nova: ${p.name}. A trilha de progressão mostra o que ainda vem.`,
      unavailable: (p: Record<string, string | number>) =>
        `${p.player} está fora de ${p.event} — visto, saúde, vida. O sub entra com a química dele; sem sub, um contratado tampa o buraco.`,
      standIn: (p: Record<string, string | number>) =>
        `Um substituto contratado mantém a org no ${p.event}. Escalação completa, química zero — e dá para notar.`,
      backerIn: () =>
        `O piso rompeu e o aporte do investidor caiu. O reembolso sai descontado da premiação até quitar. Não existe segundo resgate.`,
      insolvency: () =>
        `O segundo colapso. Salários sem pagar, cadeiras vazias, servidores no escuro — a história da org termina no livro-caixa.`,
      seasonChampion: (p: Record<string, string | number>) =>
        `${p.org} levantam o troféu do ${p.event}. A régua de todo mundo acabou de subir.`,
      incomingBid: (p: Record<string, string | number>) =>
        `${p.org} querem ${p.player} e puseram dinheiro na mesa. A decisão — e as consequências — são suas.`,
      gearBought: (p: Record<string, string | number>) =>
        `O upgrade de ${p.name} chegou. A eficiência de treino sobe — os jogadores notaram na hora.`,
      bootcampRun: () =>
        `Uma semana sob o mesmo teto faz o que agenda nenhuma faz: o elenco joga como se dividisse um cérebro. Próximo oficial mais afiado, e mais entrosados para sempre.`,
      coachHired: (p: Record<string, string | number>) =>
        `${p.coach} assume o quadro branco de ${p.org}. Ritmo de desenvolvimento e preparação de jogo agora respondem ao banco.`,
      scrimWin: (p: Record<string, string | number>) =>
        `Um set limpo de portas fechadas contra ${p.opponent}. Reps no bolso, química em alta, nada vazou para o plantão — quase.`,
      scrimLoss: (p: Record<string, string | number>) =>
        `${p.opponent} levou o set de scrim. Derrota de portas fechadas é a lição mais barata dos esports.`,
      blockbusterBid: (p: Record<string, string | number>) =>
        `${p.org} vieram com intenção real por ${p.player}. A história quer essa transferência — você decide se ela acontece.`,
      repDown: (p: Record<string, string | number>) =>
        `As expectativas foram declaradas e não cumpridas; o prestígio de ${p.org} sente. Reputação se recupera do mesmo jeito que se constrói.`,
    },
  },

  club: {
    title: "Clube",
    identity: "Identidade",
    manager: "Manager",
    founded: "Fundada em",
    region: "Região",
    reputation: "Reputação",
    repNext: (v: number, label: string) => `Próximo em ${v}: ${label}`,
    stars: "Rating do time",
    starLabel: (n: number) => `Org ${n} estrelas`,
    trophies: "Sala de troféus",
    trophyEmpty: "A prateleira está esperando.",
    worldsPedestal: "O pedestal do Worlds",
    records: "Recordes",
    recordPrize: "Premiação total",
    recordSeries: "Retrospecto em séries",
    recordBiggestFee: "Maior contratação",
    recordTitles: "Títulos",
    seasonHistory: "Histórico de temporadas",
    editColors: "Re-tintar cores",
    progression: "Progressão",
    progressionDesc: "Tudo o que ainda está pela frente desta org.",
    unlockAt: (v: number) => `Desbloqueia com ${v} de Reputação`,
    unlockWorlds: "Desbloqueia com uma vaga no Worlds",
    unlockFuture: "Atualização futura",
    unlocked: "Desbloqueado",
    unlockables: {
      peripherals: "Periféricos pro",
      monitors: "Monitores 240Hz",
      pcs: "PCs de torneio",
      bootcamp1: "Bootcamp",
      bootcamp2: "Bootcamp estruturado",
      psychologist: "Psicóloga esportiva",
      perfCenter: "Centro de Performance",
      t2: "Circuito de Invitationals",
      sponsorT2: "Patrocinadores Challenger",
      sponsorT3: "Patrocinadores globais",
      sponsorT4: "Parceiros de título",
      relocation: "Mudança de região",
      star5: "Status 5 estrelas",
    },
    editCrest: "Editar escudo",
    settings: "Opções da carreira",
    abandonCareer: "Abandonar carreira",
    abandonConfirm: "Isto apaga o save permanentemente. Os troféus vão junto.",
  },

  event: {
    lobbyTitle: "Lobby do evento",
    format: "Formato",
    formatSwiss: "Swiss de 16 times → top-8 em eliminação dupla",
    formatSingle: "Mata-mata de 8 times",
    yourSeed: (n: number) => `Seed nº ${n}`,
    watch: "Jogar a série",
    instant: "Resultado instantâneo",
    simToEnd: "Simular até o fim",
    skipSeries: "Pular série",
    lockIn: "Confirmar escalação",
    lineupLocked: "Escalação travada para o evento",
    roundLabel: (n: number) => `Rodada ${n}`,
    swissStage: "Fase Swiss",
    playoffs: "Playoffs",
    grandFinal: "Grande Final",
    thirdPlace: "Terceiro lugar",
    semifinal: "Semifinal",
    quarterfinal: "Quartas de final",
    upperBracket: "Chave superior",
    lowerBracket: "Chave inferior",
    game: (n: number) => `Jogo ${n}`,
    goal: "GOL",
    overtime: "PRORROGAÇÃO",
    matchPoint: "Match point",
    deciding: "Jogo decisivo",
    upset: "ZEBRA",
    seriesWin: (name: string) => `${name} levam a série`,
    sweep: "Uma varrida limpa",
    reverseSweep: "REVERSE SWEEP",
    eliminated: "Sua campanha termina aqui",
    advancing: "Avança para a próxima rodada",
    champion: (name: string) => `${name} — CAMPEÕES`,
    yourResult: (placement: string) => `Colocação final: ${placement}`,
    earned: "Conquistado",
    unavailableNotice: (player: string) => `${player} está fora desta — próximo da fila.`,
    aiTicker: "Pelo chaveamento",
    speed: "Velocidade",
    // Reconstrução v0.2 — classificação ao vivo, chaveamento, match center
    standings: "Classificação",
    bracket: "Chaveamento",
    matchCenter: "Match center",
    throughRound: (n: number) => `Até a rodada ${n}`,
    record: "V-D",
    gameDiff: "SG",
    advancedTag: "Classificado",
    eliminatedTag: "Fora",
    liveTag: "AO VIVO",
    nextUp: "A seguir",
    yourMatch: "Sua série",
    starOfSeries: (name: string) => `Destaque da série: ${name}`,
    scorerLine: (name: string, n: number) => `${name} ×${n}`,
    resultsDigest: "Resumo de resultados",
    digestPlacement: "Colocação",
    digestPrize: "Premiação",
    digestPoints: "Pontos da Temporada",
    digestRep: "Reputação",
    digestTopScorer: "Artilheiro",
    continueToHq: "Voltar ao QG",
    continueToReview: "Balanço da temporada",
    fieldTitle: "A chave",
    avgOvr: "OVR médio",
    seedLabel: "Seed",
  },

  spectate: {
    title: "Do sofá",
    watchParty: "Assistindo de casa",
    digestTitle: "Resumo de resultados",
    meaning: "O que isso significa para você",
    followedResult: (org: string, placement: string) => `${org} terminam em ${placement}`,
  },

  ceremonies: {
    splitRecap: "Resumo do split",
    saveAndRest: "Salvar e descansar",
    keepGoing: "Seguir para a janela",
    seasonReview: "Balanço da temporada",
    seasonGrade: (g: string) => `Nota da temporada: ${g}`,
    expected: (label: string) => `Esperado: ${label}`,
    delivered: (label: string) => `Entregue: ${label}`,
    devRecap: "Desenvolvimento",
    bizRecap: "Negócios",
    rolloverTitle: (label: string) => `Começa a ${label}`,
    rolloverCta: "Iniciar a temporada",
    worldsChampion: (name: string) => `${name} — CAMPEÕES MUNDIAIS`,
    yourTitle: "CAMPEÕES MUNDIAIS",
    creditsJourney: "A estrada até aqui",
    creditsRoster: "O elenco que conseguiu",
    finalWhistle: "Apito final",
    finalWhistleBody: "A temporada 2026 fecha o livro — mas não a história da org.",
    insolvencyTitle: "Insolvência",
    insolvencyBody: "As contas não sobreviveram a um segundo colapso. A história da org termina aqui.",
    legacyTitle: "Legado da carreira",
    legacyGrade: { legend: "Lenda", contender: "Contendor", challenger: "Desafiante", journeyman: "Batalhador" },
    retire: "Aposentar",
    retireDesc: "A carreira é arquivada — troféus e histórico continuam visíveis.",
    infinite: "Era infinita",
    infiniteDesc: "A linha do tempo agora é sua. Sem roteiro — só a simulação.",
    infiniteExplainer:
      "A partir de 2027 o mundo é totalmente procedural: novatos são gerados, veteranos se aposentam, a história é a que você fizer.",
    defendTitle: "Defender o título",
  },

  saves: {
    title: "Carreiras",
    empty: "Fundar uma nova org",
    resume: "Retomar",
    archived: "Arquivada",
    champion: "CAMPEÕES",
    endedInsolvent: "Insolvente",
    endedRetired: "Aposentada",
    delete: "Apagar",
    deleteConfirm: (org: string, n: number) =>
      `Apagar ${org}? ${n} temporada${n === 1 ? "" : "s"} de história somem. Permanente e local.`,
    lastPlayed: "Jogado por último",
    newCareer: "Nova carreira",
    slotsFull: "Os três espaços estão ocupados.",
  },

  goals: {
    reachMajor: "Alcançar um Major",
    regionalTop4: "Um top-4 regional",
    majorTop8: "Um top-8 de Major",
    majorTop4: "Um top-4 de Major",
    qualifyWorlds: "Classificar para o Worlds",
    worldsTop4: "Um top-4 no Worlds",
    winMajor: "Vencer um Major",
    winWorlds: "Vencer o Worlds",
    repRisk: (n: number) => `Sua reputação espera isso (−${n} se falhar)`,
  },

  explainers: {
    skipAll: "Pular todas as dicas",
    gotIt: "Entendi",
    hub: {
      title: "Este é o QG",
      body: "Aquele botão laranja toca sua carreira. O resto é profundidade opcional — a org funciona mesmo se você só apertar Continuar.",
    },
    calendar: {
      title: "A temporada num relance",
      body: "Três splits, três regionais cada, um Major fechando cada split. Os Pontos da Temporada decidem quem vai ao Major — e ao Worlds.",
    },
    squad: {
      title: "Seu elenco",
      body: "Três titulares e um sub. Mantenha um núcleo junto e a química paga; troque demais e a tabela lembra.",
    },
    training: {
      title: "Treinos",
      body: "Os jogadores evoluem rumo ao potencial toda semana. O coach pode cuidar disso por você — assuma quando quiser.",
    },
    market: {
      title: "O mercado",
      body: "Contrate agentes livres ou compre contratos — só com a janela aberta. Todo preço mostra sua conta.",
    },
    window: {
      title: "Janela de transferências",
      body: "As janelas ficam entre os splits (mais uma última chamada antes do Worlds). Negócios resolvem quando você avança a semana.",
    },
    finances: {
      title: "As contas",
      body: "Premiações e patrocínios entram, salários e manutenção saem, pagamento a cada split. Quebrou uma vez, um investidor salva. Uma vez.",
    },
    standings: {
      title: "A linha de corte",
      body: "A linha tracejada é o corte de classificação. Tudo pelo que a org luta se mede contra ela.",
    },
    sponsor: {
      title: "Patrocinadores",
      body: "Dinheiro garantido por split, bônus se bater a meta. Falhar nunca custa caixa — falhar repetidamente custa o nível da renovação.",
    },
    randomEvent: {
      title: "Próximo da fila",
      body: "Às vezes um titular não pode jogar — visto, saúde, vida. O sub entra com a química dele; sem sub, um contratado de emergência mantém você no chaveamento.",
    },
    worldsRace: {
      title: "A corrida pelo Worlds",
      body: "Os Pontos da Temporada de cada regional e Major acumulam o ano todo. Termine acima da linha da sua região e o maior palco se abre.",
    },
    rollover: {
      title: "Virada de temporada",
      body: "As idades avançam, os contratos contam, o mundo se reorganiza rumo à própria história — a menos que você já a tenha mudado.",
    },
  },

  common: {
    ovr: "OVR",
    pot: "POT",
    ovrShort: (n: number) => `${n} OVR`,
    starsShort: (n: number) => `${n}★`,
    rep: "Rep",
    reputation: "Reputação",
    seasonPoints: "Pontos da Temporada",
    prize: "Premiação",
    confirm: "Confirmar",
    cancel: "Cancelar",
    back: "Voltar",
    next: "Avançar",
    close: "Fechar",
    locked: "Bloqueado",
    free: "Grátis",
    perSplit: "/ split",
    you: "Você",
    placement: {
      champion: "Campeões",
      runner_up: "Vice-campeões",
      third: "3º lugar",
      fourth: "4º lugar",
      top4: "Top 4",
      top6: "Top 6",
      top8: "Top 8",
      swiss_exit: "Eliminado no Swiss",
    },
    tier: {
      t3: "Community Cup",
      t2: "Invitational",
      regional: "Regional",
      major: "Major",
      worlds: "Worlds",
    },
    difficultyNote: "A dificuldade molda adversários e dinheiro — nunca quem você pode contratar.",
  },
};
