/**
 * PT-BR dictionary — mirrors the shape of `copy.en.ts` exactly.
 * Tone: narração de transmissão / análise pós-jogo (esports BR). Termos que a
 * comunidade brasileira de Rocket League costuma manter em inglês ficam como
 * estão (draft, reroll, run, overall, clutch, OT, playoffs, MVP).
 */

import type { Copy } from "./copy.en";

export const PT: Copy = {
  APP: {
    name: "Rocket Draft",
    tagline: "Drafte a história. Sobreviva à chave.",
    description:
      "Um jogo fan-made de draft da história do Rocket League esports. Monte um elenco com lineups icônicas da RLCS e dispute um torneio no estilo RLCS.",
    disclaimer:
      "Projeto fan-made, sem fins lucrativos, para fins educativos. Não afiliado à Psyonix, Epic Games ou qualquer organização de esports. Rocket League é marca registrada de seus respectivos donos.",
  },

  NAV: {
    home: "Início",
    play: "Jogar",
    collection: "Coleção",
    profile: "Perfil",
    settings: "Config",
  },

  HOME: {
    playClassic: "Draft Clássico",
    playClassicDesc: "3 jogadores, técnico, reserva e org. Suíça e playoffs de dupla eliminação.",
    quickDraft: "Draft Rápido",
    quickDraftDesc: "Só jogadores, chave curta. Feito para partidas rápidas.",
    daily: "Desafio Diário",
    dailyDesc: "Um draft com seed por dia, igual para todos.",
    dailyPlay: "Jogar o desafio de hoje",
    dailyVictory: "Vitória",
    dailyDefeat: "Derrota",
    dailyComeBack: "Volte amanhã para um novo desafio.",
    dailyStreak: (n: number) => `${n} vitórias seguidas`,
    comingSoon: "Em breve",
    collection: "Coleção",
    collectionDesc: "Cartas especiais que você desbloqueou nas suas runs.",
    achievements: "Conquistas",
    achievementsDesc: "Feitos para perseguir em cada run.",
    profile: "Perfil",
    profileDesc: "Rank, XP e histórico de runs.",
    howToPlay: "Como jogar",
    joinDiscord: "Entrar no Discord",
    support: "Me pague um café",
    liveBadge: "No ar",
    playNow: "Jogar agora →",
    runs: (n: number) => `${n} ${n === 1 ? "run" : "runs"}`,
    titles: (n: number) => `${n} títulos`,
  },

  NAV_UI: {
    backToMenu: "Voltar ao menu",
    changelog: "Novidades",
    privacy: "Privacidade",
    howToPlay: "Como jogar",
    discord: "Discord",
    support: "Apoiar o projeto",
    madeBy: "Feito por",
    inspiredBy: "Inspirado em",
    by: "por",
  },

  RUN_UI: {
    reset: "Resetar run",
    resetTitle: "Resetar esta run?",
    resetBody:
      "Seu draft e progresso no torneio serão descartados e um novo draft começa na mesma dificuldade.",
    resetConfirm: "Resetar run",
    resetCancel: "Continuar jogando",
    phaseDraft: "Draft",
    phaseReview: "Revisão",
    phaseTournament: "Torneio",
    phaseResults: "Resultados",
    hiddenOvr: "OVR oculto",
  },

  SETUP: {
    title: "Configuração da Partida",
    subtitle:
      "Escolha uma dificuldade. O pool do draft é sempre totalmente aleatório — a dificuldade muda o torneio, não a sua sorte.",
    difficulty: "Dificuldade",
    showOverall: "Mostrar overalls durante o draft",
    showOverallHint:
      "Desligue para draftar só no conhecimento. Os overalls são revelados na tela de resultados.",
    overallLocked: "Travado oculto nesta dificuldade",
    rerolls: (n: number) => (n === 1 ? "1 reroll" : `${n} rerolls`),
    start: "Começar Draft",
    back: "Voltar ao menu",
    legacyLocked: "Vença um torneio no Difícil para desbloquear o Legacy.",
    mode: "Modo de jogo",
    modeClassic: "Draft Clássico",
    modeClassicHint: "6 vagas · suíça + playoffs de dupla eliminação",
    modeQuick: "Draft Rápido",
    modeQuickHint: "só 3 jogadores · chave direta de 8 times",
    ovrOptional: "OVR opcional",
    ovrHidden: "OVR oculto",
    selected: "Selecionado",
    legacyBadge: "Gauntlet histórico",
  },

  DIFFICULTY_LABELS: {
    easy: { label: "Fácil", tagline: "Aprenda o ritmo. Variância perdoadora, chave mais amigável." },
    normal: { label: "Normal", tagline: "A experiência RLCS padrão. Campo equilibrado." },
    hard: { label: "Difícil", tagline: "Overalls ocultos. Campo mais forte. Conhecimento vence." },
    legacy: { label: "Legacy", tagline: "Um gauntlet histórico de elencos campeões." },
  },

  DRAFT_UI: {
    pickProgress: (filled: number, total: number) =>
      `Escolha ${Math.min(filled + 1, total)} de ${total}`,
    roundLabel: (n: number) => `Lineup ${n}`,
    reroll: "Reroll",
    rerollsLeft: (n: number) => (n === 1 ? "1 restante" : `${n} restantes`),
    noRerolls: "Sem rerolls",
    freeReroll: "Reroll grátis",
    freeRerollHint: "Nada aqui serve para suas vagas restantes — esse é por nossa conta.",
    selectHint: "Toque numa carta para draftar — ela vai para a primeira vaga livre",
    yourRoster: "Seu Time",
    slotPlayer: (n: number) => `Jogador ${n}`,
    slotCoach: "Técnico",
    slotSub: "Reserva",
    slotOrg: "Org",
    empty: "Vazio",
    slotFull: "Vagas cheias",
    alreadyDrafted: "Já draftado",
    stillNeeded: "Ainda falta",
    hiddenOverall: "??",
    noCoach: "Sem Técnico",
    noSub: "Sem Reserva",
    notFielded: "Não atuou nesta season",
    player: "Jogador",
  },

  ONBOARDING: {
    howToTitle: "Como jogar",
    howToIntro: "Monte um elenco com a história da RLCS e dispute a chave. O básico:",
    howToSteps: [
      "A cada rodada sai uma lineup histórica da RLCS. Toque numa carta para draftá-la no seu time.",
      "Preencha 3 jogadores, um técnico, um reserva e uma org. A química recompensa juntar companheiros de time, países e orgs.",
      "Então um torneio joga sozinho: suíça e playoffs de dupla eliminação. Mais overall + química vence mais séries.",
      "Termine as runs — vencendo ou perdendo — para ganhar XP, subir de rank e desbloquear cartas especiais para sua coleção.",
    ],
    howToCta: "Bora draftar",
    legacyTitle: "Bem-vindo ao Legacy",
    legacyIntro: "Você desbloqueou o gauntlet histórico. Ele é diferente:",
    legacySteps: [
      "O campo está lotado dos maiores elencos campeões da história da RLCS.",
      "Os overalls ficam ocultos e não há rerolls — você drafta só no conhecimento.",
      "Vença aqui e você terá batido os melhores dos melhores. Boa sorte.",
    ],
    legacyCta: "Pode vir",
  },

  REVIEW: {
    title: "Revisão do Time",
    subtitle: "Conferida final antes do torneio. As escolhas estão travadas.",
    teamOverall: "Overall do Time",
    chemistry: "Química",
    orgBonus: "Bônus da Org",
    specialEffects: "Efeitos Especiais",
    noSpecials: "Nenhuma carta especial neste elenco.",
    breakdown: "Ligações de química",
    noChemistry: "Nenhuma ligação de química encontrada. Este elenco é um mix de all-stars puro.",
    readout: "Leitura do Analista",
    startTournament: "Começar Torneio",
    hiddenNote: "Os overalls ficam ocultos até a tela de resultados.",
    rowPlayers: "Jogadores (média)",
    rowCoach: "Técnico",
    rowSub: "Reserva",
    rowOrg: "Organização",
    rowChemistry: "Química",
    rowSpecials: "Especiais",
    statHigh: {
      offense: "Forte pressão ofensiva.",
      defense: "Difícil de furar.",
      mechanics: "Teto mecânico de elite.",
      consistency: "Base confiável, série após série.",
      experience: "Muita experiência de palco grande.",
      clutch: "Feito para jogos decisivos.",
    },
    statLow: {
      offense: "Pode ter dificuldade de criar chances.",
      defense: "Exposto na defesa às vezes.",
      mechanics: "Teto mecânico limitado.",
      consistency: "Sujeito a resultados voláteis.",
      experience: "Pouca experiência de palco grande.",
      clutch: "Não testado em jogos decisivos.",
    },
    chemistryLine: (tier: string) => `Química ${tier} entre as peças.`,
    orgBrings: (org: string, stat: string, level: string) =>
      `${org} traz ${stat} ${level} para o time.`,
    oneSpecial: "Um efeito de carta especial está ativo nesta run.",
    manySpecials: (n: number) => `${n} efeitos de cartas especiais estão ativos nesta run.`,
  },

  TOURNAMENT_UI: {
    title: "Campeonato Estilo RLCS",
    swiss: "Fase Suíça",
    playoffs: "Playoffs",
    round: (n: number) => `Rodada ${n}`,
    record: (w: number, l: number) => `${w} – ${l}`,
    start: "Iniciar simulação",
    resume: "Retomar simulação",
    pause: "Pausar",
    speed: (x: number) => `${x}×`,
    skipAll: "Pular para o fim",
    live: "Ao vivo",
    standings: "Classificação",
    throughRound: (n: number) => `Até a Rodada ${n}`,
    yourPath: "Seu Caminho",
    matchCenter: "Central de Partidas",
    upcoming: "A seguir",
    bestOf: (n: number) => `Melhor de ${n}`,
    advanced: "Avançou",
    eliminated: "Eliminado",
    bracket: "Chave dos Playoffs",
    upperBracket: "Chave Superior",
    lowerBracket: "Chave Inferior",
    finals: "Finais",
    tbd: "A definir",
    toResults: "Ver resultados",
    reviewHint: "Clique em qualquer série finalizada para revê-la.",
    game: (n: number) => `Jogo ${n}`,
    overtime: "OT",
    matchPoint: "Match point",
    opponentHidden: "Os ratings do oponente ficam ocultos até a tela de resultados.",
    team: "Time",
    roundNames: {
      ub_quarterfinal: "Quartas (Sup)",
      lb_round1: "Inferior R1",
      ub_semifinal: "Semi (Sup)",
      lb_round2: "Inferior R2",
      ub_final: "Final (Sup)",
      lb_semifinal: "Semi (Inf)",
      lb_final: "Final (Inf)",
      third_place: "Terceiro Lugar",
      grand_final: "Grande Final",
      quarterfinal: "Quartas",
      semifinal: "Semifinal",
      final: "Final",
    },
  },

  RESULTS_UI: {
    title: "Run Completa",
    champion: "Campeões",
    championSub: "Seu elenco conquista o título.",
    runnerUp: "Vice-campeões",
    runnerUpSub: "A uma série do troféu.",
    third: "Terceiro Lugar",
    thirdSub: "No pódio após a decisão de bronze.",
    fourth: "Quarto Lugar",
    fourthSub: "Perdeu a decisão de bronze — ainda assim uma campanha longa.",
    top4: "Top 4",
    top4Sub: "A uma série da final.",
    top6: "Top 6",
    top6Sub: "A chave inferior encerrou a run.",
    top8: "Top 8",
    top8Sub: "Chegou aos playoffs, caiu no primeiro obstáculo.",
    swissExit: "Eliminado na Suíça",
    swissExitSub: "A chave fica fora de alcance desta vez.",
    swissRecord: "Campanha na suíça",
    finalPlacement: "Colocação final",
    champion0f: (name: string) => `${name} acabou levando o título.`,
    untouchableNote: "Nenhum gol sofrido na run inteira. Histórico.",
    untouchableBadge: "Intocável",
    teamOvrBadge: (n: number) => `OVR do time ${n}`,
    chemistryBadge: (tier: string) => `Química ${tier}`,
    teamReveal: "Revelação do Time",
    bestPlayer: "Melhor jogador",
    biggestWin: "Maior vitória",
    closestSeries: "Série mais apertada",
    worstLoss: "Derrota mais dura",
    ovr: (n: number) => `OVR ${n}`,
    unlocked: "Novas cartas desbloqueadas",
    unlockedNote: "adicionadas à sua coleção.",
    achievements: "Conquistas",
    achievementToast: "Conquista desbloqueada",
    xpGained: "XP ganho",
    difficultyMultiplier: "Multiplicador de dificuldade",
    hiddenOverallBonus: "Bônus de overall oculto",
    total: "Total",
    rankProgress: "Progresso de rank",
    rankUpBadge: "Subiu de rank!",
    xpToNext: (n: number, label: string) => `${n} XP para ${label}`,
    playAgain: "Jogar de novo",
    backHome: "Voltar ao menu",
    hiddenReveal: "Overalls revelados",
    share: "Baixar card de compartilhamento",
    immaculateBadge: "Run impecável",
    ceremonyKicker: "Nova carta desbloqueada",
    ceremonyTap: "Toque em qualquer lugar para revelar",
    ceremonyContinue: "Continuar",
    ceremonyNext: "Próxima carta",
    rankUpKicker: "Subiu de rank",
    rankUpTitle: "Subiu de rank!",
    rankUpHint: "Toque em qualquer lugar para continuar",
    legacyKicker: "Novo modo desbloqueado",
    legacyTitle: "Legacy Desbloqueado",
    legacySub: "Um gauntlet histórico de elencos campeões agora espera por você.",
    legacyHint: "Toque em qualquer lugar para continuar",
    eliminatorKicker: "Quem encerrou sua run",
    eliminatedBy: (name: string) => `Eliminado por ${name}`,
    eliminatorScore: (a: number, b: number) => `${a}–${b}`,
  },

  COLLECTION_UI: {
    title: "Coleção",
    subtitle:
      "Cartas especiais são desbloqueadas ao draftá-las e terminar a run — vencendo ou perdendo.",
    progress: (n: number, total: number) => `${n}/${total} desbloqueadas`,
    filters: { all: "Todas", locked: "Bloqueadas", unlocked: "Desbloqueadas" },
    rarity: "Raridade",
    type: "Tipo",
    lockedCard: "Bloqueada",
    lockedHint: "Drafte esta carta e termine a run para desbloqueá-la.",
    unlockedOn: (date: string) => `Desbloqueada em ${date}`,
    effect: "Efeito especial",
    context: "O momento",
    empty: "Nada aqui ainda. Termine runs com cartas especiais para crescer o álbum.",
  },

  SETTINGS_UI: {
    title: "Configurações",
    subtitle: "Ajuste a sensação do jogo. Salvo neste dispositivo.",
    soundSection: "Som",
    soundEnabled: "Efeitos sonoros",
    soundEnabledHint: "Sons sutis em drafts, revelações e resultados.",
    volume: "Volume",
    motionSection: "Movimento",
    reducedMotion: "Reduzir movimento",
    reducedMotionHint: "Minimiza animações (também segue a configuração do sistema).",
    animSpeed: "Velocidade das animações",
    animSpeedHint: "Quão rápido as revelações, o reel do draft e o torneio acontecem.",
    speedSlow: "Lenta",
    speedNormal: "Normal",
    speedFast: "Rápida",
    languageSection: "Idioma",
    language: "Idioma",
    reset: "Resetar configurações",
  },

  PROFILE_UI: {
    title: "Perfil",
    career: "Carreira",
    rank: "Rank",
    xp: "XP",
    toNext: (n: number) => `${n} XP para o próximo rank`,
    maxRank: "Rank máximo alcançado",
    runs: "Runs completas",
    titles: "Títulos",
    bestClear: "Melhor dificuldade vencida",
    specials: "Especiais coletadas",
    titleRate: "Taxa de títulos",
    playoffRate: "Taxa de playoffs",
    podiums: "Pódios",
    swissWins: "Vitórias na suíça",
    achievements: "Conquistas",
    viewAll: (n: number, total: number) => `${n}/${total} — ver todas`,
    history: "Histórico de runs",
    emptyHistory: "Nenhuma run ainda. Sua história começa no primeiro draft.",
    hidden: "Oculto",
    reset: "Resetar todo o progresso",
    resetConfirmTitle: "Resetar todo o progresso?",
    resetConfirmBody:
      "XP, rank, coleção, conquistas e histórico de runs serão apagados permanentemente neste dispositivo.",
    resetConfirm: "Apagar tudo",
    cancel: "Cancelar",
    none: "—",
    placement: {
      champion: "Campeão",
      runner_up: "Finalista",
      third: "3º Lugar",
      fourth: "4º Lugar",
      top4: "Top 4",
      top6: "Top 6",
      top8: "Top 8",
      swiss_exit: "Suíça",
      semifinalist: "Top 4",
      quarterfinalist: "Top 8",
    },
  },

  ACH_UI: {
    kicker: "Feitos para perseguir em cada run",
    title: "Conquistas",
  },

  HOWTO: {
    kicker: "Regras do jogo",
    title: "Como Jogar",
    steps: [
      {
        title: "Drafte seu elenco",
        body: "A cada rodada aparece uma lineup histórica real da RLCS. Pegue exatamente uma carta — um jogador, o técnico, o reserva ou a organização. O pool de lineups é sempre totalmente aleatório, em toda dificuldade.",
      },
      {
        title: "Escolha livre, seis vagas",
        body: "Você precisa de 3 jogadores, 1 técnico, 1 reserva e 1 org. Escolha em qualquer ordem. Uma vez que uma pessoa está no seu elenco, as outras versões dela não podem ser draftadas de novo nesta run. Se nada numa lineup serve para suas vagas restantes, o reroll é grátis.",
      },
      {
        title: "Construa química",
        body: "A mesma lineup histórica é a ligação mais forte, o mesmo país é forte, a mesma organização também conta. Técnicos e reservas ligados aos seus jogadores somam um pouco mais. A química soma rating — mais nas dificuldades altas.",
      },
      {
        title: "Sobreviva à chave",
        body: "16 times. Fase suíça em melhor de 5: 3 vitórias para avançar, 3 derrotas e você está fora. O Top 8 entra numa chave de dupla eliminação em melhor de 7 — uma derrota na chave superior te joga para a inferior, não para fora do evento. O rating do seu time vem principalmente dos overalls dos jogadores — química, buffs de org, técnico e efeitos especiais dão a vantagem.",
      },
      {
        title: "Colecione cartas especiais",
        body: "Versões especiais raras das cartas podem aparecer em qualquer draft: momentos icônicos, campanhas de MVP, lendas. Drafte uma e termine a run — vencendo ou perdendo — e ela é desbloqueada na sua coleção para sempre.",
      },
    ],
    difficultiesTitle: "Dificuldades",
    unlockable: "Desbloqueável",
    reroll: (n: number) => `${n} reroll${n === 1 ? "" : "s"}`,
    ovrLockedHidden: "OVR travado oculto",
    ovrOptional: "OVR opcional",
    xpMult: (x: number) => `XP ×${x}`,
    raritiesTitle: "Raridades das cartas",
    raritySilver: "Prata",
    rarityGold: "Ouro",
    rarityBlue: "Azul",
    raritiesBefore: "Cartas base são ",
    raritiesMid1: " (79 ou menos), ",
    raritiesMid2: " (80–89) e ",
    raritiesAfter:
      " (90+). Com overalls ocultos, cartas base ficam pretas e mostram ?? — cartas especiais mantêm o visual, mas o número fica oculto até a tela de resultados.",
    startFirst: "Comece seu primeiro draft",
  },

  NARRATION: {
    seriesWin: [
      "Seu time fecha a série com folga.",
      "Série tranquila. A diferença apareceu no placar.",
      "Execução limpa do início ao fim.",
    ],
    seriesWinClose: [
      "Seu time sobrevive a uma série completa.",
      "Veio na menor das margens.",
      "Um jogo decisivo com tudo em jogo — e seu elenco entrega.",
    ],
    seriesLoss: [
      "Seu time não conseguiu fechar a série.",
      "O oponente ditou o ritmo o tempo todo.",
      "Uma série dura. O botão de reset existe por um motivo.",
    ],
    seriesLossClose: [
      "Um jogo de diferença. Essa vai doer.",
      "Um jogo decisivo escapa no fim.",
      "A centímetros da vitória — a série vai para o outro lado.",
    ],
    upsetWin: [
      "O elenco menos cotado encontra a zebra.",
      "Ninguém tinha essa no radar — seu time derruba o favorito.",
    ],
    upsetLoss: [
      "Zebra no placar — o favorito cai.",
      "Seu elenco é pego por um time jogando acima do rating.",
    ],
    overtimeNote: "A prorrogação decidiu.",
    clutchNote: "O fator clutch decidiu o jogo decisivo.",
    specialNote: "Um efeito de carta especial ativou.",
    starLine: (name: string) => `${name} liderou o ataque.`,
    starLineOpponent: (name: string) => `${name} estava em todo lugar pela oposição.`,
    chemistryNote: "A química fez a diferença num confronto apertado.",
    coachNote: "O bônus do técnico ajudou a estabilizar a run.",
  },

  STAT_LABELS: {
    offense: "Ataque",
    defense: "Defesa",
    mechanics: "Mecânica",
    consistency: "Consistência",
    experience: "Experiência",
    clutch: "Clutch",
  },

  SPECIAL_TYPE_LABELS: {
    moment: "Momento",
    major_mvp: "MVP de Major",
    worlds_mvp: "MVP do Mundial",
    mythic: "Mítica",
    legend: "Lenda",
    coach: "Técnico",
    masked: "Especial",
  },

  RARITY_LABELS: {
    common: "Comum",
    silver: "Prata",
    gold: "Ouro",
    blue: "Azul",
    rare: "Rara",
    epic: "Épica",
    mythic: "Mítica",
    legendary: "Lendária",
  },

  EFFECT_LABELS: {
    clutch_boost: "Clutch (jogos decisivos)",
    swiss_consistency: "Consistência (fase suíça)",
    playoff_experience: "Experiência (playoffs)",
    upset_boost: "Fator zebra (vs times mais cotados)",
    defense_stability: "Estabilidade defensiva",
    high_roll: "Teto mecânico",
  },

  CHEM_TIERS: {
    Poor: "Fraca",
    Okay: "Ok",
    Good: "Boa",
    Great: "Ótima",
    Perfect: "Perfeita",
  },
};
