/**
 * Road to Worlds — English copy (career mode).
 *
 * One grouped object, read ONLY by career code through `useCareerCopy()` /
 * `getCareerCopy()` (`careerCopy.ts`) — it is deliberately not part of the
 * core EN dictionary, so draft-game pages never download it. Do not import
 * this file from non-career modules; the home card's strings are in
 * `HOME.career*` (copy.en.ts / copy.pt.ts).
 * `copy.career.pt.ts` mirrors this shape exactly (enforced by its type).
 * Tone: broadcast desk / post-match analysis — clean esports language.
 */

export const CAREER_EN = {
  meta: {
    title: "Road to Worlds",
    nav: "Career",
    locked: "Available soon",
  },

  nav: {
    hub: "HQ",
    calendar: "Calendar",
    squad: "Squad",
    training: "Training",
    market: "Market",
    finances: "Finances",
    standings: "Standings",
    news: "Inbox",
    club: "Club",
    more: "More",
    exit: "Exit to menu",
    saves: "Careers",
  },

  // v0.2 day clock — date rendering (Monday-start weeks).
  dates: {
    months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    weekdaysLong: [
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
      "Sunday",
    ],
    /** e.g. "Sat, Oct 24" */
    short: (dow: string, month: string, d: number) => `${dow}, ${month} ${d}`,
    /** e.g. "Oct 24" */
    tiny: (month: string, d: number) => `${month} ${d}`,
    today: "Today",
    tomorrow: "Tomorrow",
    inDays: (n: number) => `in ${n} days`,
    daysShort: (n: number) => `${n}d`,
  },

  wizard: {
    title: "Found your organization",
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    quickStart: "Quick start",
    quickStartHint: "Randomize everything — you can re-tint colors later.",
    // Step 1 — identity
    identityTitle: "Identity",
    identityKicker: "Every dynasty starts with a name on a jersey.",
    orgName: "Organization name",
    orgNamePlaceholder: "e.g. Horizon Esports",
    orgNameTaken: "That name belongs to an existing org.",
    orgNameLength: "2-18 characters.",
    abbrev: "Tag",
    abbrevHint: "2-4 letters, shown on tables and the crest.",
    managerName: "Manager name",
    managerNamePlaceholder: "Your name on the desk.",
    country: "Country",
    // Step 2 — crest (v0.2: shapes × symbols × patterns × free colors)
    crestTitle: "Crest & colors",
    crestKicker: "Pick a mark. The scene will learn to fear it.",
    crestLabel: "Shape",
    crestSymbol: "Symbol",
    crestPattern: "Pattern",
    crestNone: "None",
    randomizeCrest: "Randomize",
    primaryColor: "Primary color",
    secondaryColor: "Accent",
    identityBuff: "Org identity",
    identityBuffHint: "Your org's specialty — a small team-wide edge.",
    // Step 3 — region
    regionTitle: "Home region",
    regionKicker: "Where you play decides who you face — and how many Worlds seats exist.",
    regionStrength: "Field strength",
    regionSlots: (n: number) => `${n} Worlds slots`,
    regionRivals: "Notable rivals",
    regionNote: "Relocating to another region unlocks later in the career.",
    strengthDeep: "Deep field — the hard road",
    strengthStrong: "Strong field",
    strengthDeveloping: "Developing field — a softer road",
    // Step 4 — roster
    rosterTitle: "First signings",
    rosterKicker: "Three players without an org. One of them says yes to yours.",
    rosterProspects: "Prospects",
    rosterProspectsDesc: "Teenagers with sky-high ceilings. Patience required.",
    rosterJourneymen: "Journeymen",
    rosterJourneymenDesc: "The scene's veterans. Ready now, done growing.",
    rosterBalanced: "Balanced",
    rosterBalancedDesc: "A bit of now, a bit of later.",
    recommended: "Recommended",
    wageBill: "Wage bill",
    avgAge: "Avg age",
    avgOverall: "Avg OVR",
    // Step 5 — difficulty + summary
    finalTitle: "Final call",
    finalKicker: "Difficulty shapes opponents and money pressure — never who you can sign.",
    styleTitle: "Management style",
    styleHandsOn: "Hands-on",
    styleHandsOnDesc: "You set every focus, every offer, every lineup.",
    styleBalanced: "Balanced",
    styleBalancedDesc: "Smart defaults, recommendations highlighted. You confirm.",
    styleDelegate: "Delegate",
    styleDelegateDesc: "The coach handles routine — every action reported, takeover any time.",
    summaryTitle: "The paperwork",
    found: (org: string) => `Found ${org}`,
    founded: "EST. 2020",
    foundedSplash: "A new name enters the scene.",
  },

  hub: {
    title: "HQ",
    continue: "Continue",
    continueTo: (label: string) => `Advance — ${label}`,
    advanceDay: "Advance one day",
    nowNext: "Next up",
    nowDecision: "Decision required",
    week: (n: number) => `Week ${n}`,
    matchdayIn: (n: number) => (n === 0 ? "MATCHDAY" : n === 1 ? "Matchday tomorrow" : `Matchday in ${n} days`),
    seasonGoal: "Season goal",
    goalStretch: "Stretch",
    rosterForm: "Squad",
    form: "Form",
    chemistry: "Chemistry",
    pointsRace: "Road to Worlds",
    pointsRank: (rank: number, pts: number) => `#${rank} · ${pts} pts`,
    pointsGap: (pts: number) => `${pts} pts below the line`,
    pointsSafe: "Above the cut-line",
    budget: "Balance",
    budgetNet: (s: string) => `${s} / split`,
    budgetWarning: "Projected negative by next payday",
    news: "The wire",
    newsAll: "Full feed",
    inboxTeaser: "Inbox",
    inboxAll: "Open inbox",
    sponsor: "Sponsor objective",
    trainingWeek: "Training week — squad gets extra reps",
    thisWeek: "This week",
    comingUp: "Coming up",
    quickActions: "Today at the office",
    scrimCta: (opp: string) => `Scrim vs ${opp}`,
    scrimsLeft: (n: number) => (n === 1 ? "1 scrim block left this week" : `${n} scrim blocks left this week`),
    scrimUnavailable: "No scrim block available today",
    restDay: "Rest day — the squad recharges",
    progression: "Next unlock",
    emptyStateTitle: "Welcome to the desk",
    emptyStateBody: "Your first tournament is on the calendar. Press Continue when you're ready.",
    // v0.3 FIFA-style autoplay
    play: "Play",
    pause: "Pause",
    playHint: (label: string) => `Playing — next: ${label}`,
    skipToNext: "Skip ahead",
    // v0.3 transfer wire panel
    transfersTitle: "Transfer window",
    transfersWire: "The transfer wire",
    transfersAll: "All regions",
    transfersEmpty: "No moves logged yet — the wire fills as the window runs.",
    transfersFa: "Free agent",
    transfersUser: "Your move",
    transfersShowAll: (n: number) => `Show all ${n} moves`,
  },

  // v0.2 Inbox — mail addressed to the manager (offers, sponsors, contracts).
  mail: {
    title: "Inbox",
    unread: (n: number) => `${n} unread`,
    markAllRead: "Mark all read",
    empty: "No mail. The desk is quiet — for now.",
    emptyHint: "Transfer offers, sponsorship deals and contract notices land here.",
    open: "Open",
    from: {
      board: "The Board",
      agent: "Player Agents",
      sponsor: "Sponsor Relations",
      backer: "Emergency Backer",
      league: "League Operations",
      staff: "Team Operations",
    },
    kinds: {
      offer: "Transfer",
      sponsor: "Sponsorship",
      contract: "Contracts",
      finance: "Finances",
      unlock: "Unlocked",
      club: "Club",
    },
    tpl: {
      incomingBid: (p: Record<string, string | number>) => `Offer for ${p.player}`,
      blockbusterBid: (p: Record<string, string | number>) => `BLOCKBUSTER: ${p.org} want ${p.player}`,
      sponsorOffers: () => `Sponsorship proposals on your desk`,
      objectiveHit: (p: Record<string, string | number>) => `${p.name}: objective delivered`,
      objectiveMissed: (p: Record<string, string | number>) => `${p.name}: objective missed`,
      contractExpiring: (p: Record<string, string | number>) => `${p.player} — contract in its final season`,
      backerIn: () => `Emergency funding arranged`,
      unlock: (p: Record<string, string | number>) => `New for the org: ${p.name}`,
      windowReport: (p: Record<string, string | number>) => `Window report: ${p.n} moves`,
      unavailable: (p: Record<string, string | number>) => `${p.player} out for ${p.event}`,
      debtCleared: () => `Backer repaid in full`,
    },
    body: {
      incomingBid: (p: Record<string, string | number>) =>
        `${p.org} tabled a formal offer of ${p.fee} for ${p.player}. It expires when the window closes — accept or decline it in the Market's deals tab.`,
      blockbusterBid: (p: Record<string, string | number>) =>
        `${p.org} came in heavy: ${p.fee} for ${p.player}. Refusing a bid this size can raise his next renewal ask — but nobody sells their core for free.`,
      sponsorOffers: () =>
        `Brands are interested in the org. Review the proposals in Finances — the base payment is guaranteed; the bonus rides on the objective.`,
      objectiveHit: (p: Record<string, string | number>) =>
        `The split objective was delivered. The bonus of ${p.bonus} lands with the payday. Good business.`,
      objectiveMissed: (p: Record<string, string | number>) =>
        `The split objective slipped. No money is clawed back — but repeated misses lower next season's renewal tier. (Misses so far: ${p.misses}.)`,
      contractExpiring: (p: Record<string, string | number>) =>
        `${p.player} is in the final season of his deal. You hold an exclusive re-sign window through Split 3 — after that, he walks for free.`,
      backerIn: () =>
        `The books breached the floor and the Emergency Backer stepped in — once. Repayment is garnished from prize money. A second collapse ends the org.`,
      unlock: (p: Record<string, string | number>) =>
        `The org's progress unlocked: ${p.name}. Check the Club's progression track — the toolbox grows with reputation.`,
      windowReport: (p: Record<string, string | number>) =>
        `The window is shut — ${p.n} moves across all regions. Headline fees: ${p.p1} (${p.f1})${p.p2 ? ` · ${p.p2} (${p.f2})` : ""}${p.p3 ? ` · ${p.p3} (${p.f3})` : ""}. The full wire is on the HQ.`,
      unavailable: (p: Record<string, string | number>) =>
        `${p.player} can't play ${p.event} — the sub steps in with his chemistry; without one, an emergency stand-in fills the seat for a fee.`,
      debtCleared: () =>
        `The Emergency Backer is repaid in full. Transfer fees and gear purchases are unlocked again — the org owns its future.`,
    },
  },

  // v0.2 scrims — weekday blocks between events. v0.3: schedulable, opponent
  // choice, visible results.
  scrim: {
    title: "Scrim block",
    desc: "A best-of-5 behind closed doors: chemistry reps and light development. Two blocks per week.",
    vs: (opp: string) => `vs ${opp}`,
    run: "Run scrim",
    won: (opp: string, a: number, b: number) => `Scrim W ${a}-${b} vs ${opp}`,
    lost: (opp: string, a: number, b: number) => `Scrim L ${a}-${b} vs ${opp}`,
    usedUp: "No scrim blocks left this week",
    restDay: "No scrims on rest days",
    // v0.3 scheduling + results
    planTitle: "Sparring partners",
    planDesc: "Pick the opponent and the day — booked scrims run automatically and show on the calendar.",
    chooseOpponent: "Opponent",
    pickDay: "Day",
    bookCta: "Book scrim",
    booked: (date: string, opp: string) => `Booked: ${date} vs ${opp}`,
    upcoming: "Booked scrims",
    cancel: "Cancel",
    benefit: "What you get",
    projGain: (n: string) => `≈ +${n} OVR per starter`,
    projChem: "+ chemistry reps",
    fieldLevel: (n: number) => `Sparring level ${n}`,
    strongerSide: "Stronger sparring develops faster",
    results: "Recent scrims",
    noResults: "No scrims yet this season.",
    gameLine: (scores: string) => `Games: ${scores}`,
    sameDay: "Already scrimmed this team today.",
  },

  calendar: {
    title: "Calendar",
    thisWeek: "This week",
    today: "Today",
    preseason: "Preseason",
    openWeek: "Open week",
    window: "Transfer window",
    worldsWindow: "Worlds window",
    windowOpen: "Window open",
    windowCloses: (n: number) =>
      n <= 0 ? "Window closes today" : n === 1 ? "Window closes tomorrow" : `Window closes in ${n} days`,
    regional: (n: number) => `Regional ${n}`,
    major: "Major",
    worlds: "World Championship",
    split: (n: number) => `Split ${n}`,
    registered: "Entered",
    notQualified: "Not qualified",
    spectate: "Watch results",
    done: "Done",
    stakes: "Stakes",
    prizePool: "Prize pool",
    points: "Season Points",
    field: "Field",
    fieldQuality: "Field level",
    enter: "Enter",
    skip: "Pass",
    skipHint: "Passing keeps the week for training (+25% efficiency).",
    offerTitle: "Tournament invite",
    seasonOverview: "Season overview",
    // v0.2 day view
    monthView: "Month",
    agendaView: "Agenda",
    nextForYou: "Next for you",
    matchday: "Matchday",
    payday: "Payday",
    trainingDay: "Training",
    restDay: "Rest",
    scrimDay: "Scrim",
    legend: "Legend",
    advanceDay: "Advance one day",
    advanceToStop: (label: string) => `Continue — ${label}`,
    seasonEnd: "Season close",
    showWorld: "Show other regions",
    hideWorld: "My schedule only",
    worldEvents: "Around the world",
  },

  squad: {
    title: "Squad",
    starters: "Starters",
    bench: "Bench",
    subSlot: "Substitute",
    coachSlot: "Coach",
    staffRow: "Staff & boosts",
    hire: "Hire",
    emptySub: "No sub — an absence costs a stand-in fee and chemistry.",
    emptyCoach: "A coach boosts development and match prep.",
    contracts: "Contracts",
    wage: "Wage",
    perSplit: (s: string) => `${s} / split`,
    expires: (label: string) => `Ends ${label}`,
    expiring: "Contract expiring",
    renew: "Renew",
    release: "Release",
    releaseFee: (s: string) => `Severance: ${s}`,
    releaseConfirm: (name: string) => `Release ${name}?`,
    releaseBody: "Severance is paid now; the wage comes off the books.",
    makeStarter: "Move to starters",
    makeSub: "Move to bench",
    swapPreview: (a: number, b: number) => `Team rating ${a} → ${b}`,
    chemPreview: (a: number, b: number) => `Chemistry ${a}% → ${b}%`,
    bestLineup: "Best lineup",
    stability: "Roster stability",
    stabilityState: (used: number, max: number) => `New faces this split: ${used}/${max}`,
    stabilityWarning: (pct: number, pts: number) =>
      `Fielding another new face costs ${pct}% of your ${pts} Season Points`,
    finalSeason: "Final season",
    squadFull: "Squad full (3 starters + 1 sub)",
  },

  player: {
    age: (n: number) => `Age ${n}`,
    potential: "Potential",
    potBand: (min: number, max: number) => `POT ${min}-${max}`,
    potExact: (v: number) => `POT ${v}`,
    overall: "Overall",
    attributes: "Attributes",
    development: "Development",
    contract: "Contract",
    history: "History",
    scoutReport: "Scout report",
    scoutCost: (s: string) => `Order report · ${s}`,
    scoutDone: "Fully scouted",
    scoutHint: "Narrows the potential range.",
    growthRoom: "Growth room",
    phase: { growing: "Developing", prime: "Prime", declining: "Declining" },
    projected: (v: string) => `Projected: ${v} by split's end`,
    trainingFocusLabel: "Training focus",
    archetype: {
      mechanical: "Mechanical",
      anchor: "Anchor",
      playmaker: "Playmaker",
      icecold: "Ice Cold",
      veteranmind: "Veteran Mind",
      allround: "All-Around",
    },
    archetypeHint: {
      mechanical: "Flashy ceiling, shaky floor.",
      anchor: "Holds the back post. Wins ugly games.",
      playmaker: "Creates for everyone. Reads the pitch first.",
      icecold: "Wants the deciding game.",
      veteranmind: "Slower hands, faster brain.",
      allround: "No holes in the kit.",
    },
    fictionalTag: "Sim player",
  },

  training: {
    title: "Training",
    autoTrain: "Delegate to coach",
    autoTrainDesc: "The coach sets each player's focus and reports results.",
    handledByCoach: "Set by coach",
    manageMyself: "Manage it myself",
    focus: "Focus",
    balanced: "Balanced",
    auto: "Auto",
    coachEffect: (name: string, pct: number) => `Coach ${name}: ${pct > 0 ? "+" : ""}${pct}% efficiency`,
    noCoach: "No coach — development runs below pace.",
    facilityEffect: (pct: number) => `Gear: +${pct}% efficiency`,
    projection: (v: string) => `+${v} OVR this split`,
    matchXpHint: "Playing strong fields develops players faster than any drill.",
    report: (delta: string) => `Training report: squad ${delta} OVR`,
    // v0.2 — distinct focuses, intensity, weekly rhythm
    weeklyPlan: "Weekly plan",
    weeklyPlanHint: "Sessions run Monday to Friday. Matchday Saturday. Sunday rests.",
    perWeekOverall: (v: string) => `+${v} OVR / week`,
    perWeekOffset: (v: string, stat: string) => `+${v} ${stat} / week`,
    focusHintBalanced: "Pure overall growth — nothing sharpened.",
    focusHintAttr: "Trades a slice of overall growth to sharpen one attribute.",
    focusHintAuto: "The coach picks each week's emphasis — near-optimal, hands-free.",
    intensity: "Intensity",
    intensityLight: "Light",
    intensityNormal: "Normal",
    intensityHeavy: "Heavy",
    intensityLightHint: "-40% development, zero fatigue risk.",
    intensityNormalHint: "The standard block.",
    intensityHeavyHint: "+35% development — adds a small, telegraphed absence risk before events.",
    fatigueWarning: "Heavy sessions raise the pre-event absence risk",
    sessionToday: "Today's session",
    noSessionToday: "No session today",
    matchPrepWeek: "Match week — sessions pause; the event pays match XP instead",
  },

  market: {
    title: "Market",
    freeAgents: "Free agents",
    contracted: "Under contract",
    myDeals: "My deals",
    windowClosed: "Market closed",
    windowClosedHint: (label: string) => `Transfer window opens ${label}`,
    scoutingOpen: "Scouting stays open between windows.",
    fee: "Transfer fee",
    signingBonus: "Signing bonus",
    freeAgentTag: "Free agent",
    ask: "Asking terms",
    whyPrice: "Why this price",
    factor: {
      overall: "Rating",
      age: "Age",
      potential: "Upside",
      repPremium: "Star premium",
      length: "Contract length",
      contract: "Under contract",
    },
    lengthLabel: "Contract length",
    seasons: (n: number) => (n === 1 ? "1 season" : `${n} seasons`),
    roleLabel: "Role",
    starter: "Starter",
    sub: "Substitute",
    signCta: "Sign",
    offerSent: "Deal registered — resolves on the next advance.",
    signed: (name: string) => `${name} signs for the org`,
    rejected: (name: string) => `${name} declined the terms`,
    recommendedShelf: "Recommended signings",
    recommendedWhy: (reason: string) => `Fits: ${reason}`,
    affordable: "Affordable now",
    incomingBid: "Incoming offer",
    bidFrom: (org: string) => `${org} bid`,
    accept: "Accept",
    decline: "Decline",
    declineHint: "Refusing a big offer can raise the player's next renewal ask.",
    blockbuster: "Blockbuster",
    consequences: "After this deal",
    balanceAfter: (s: string) => `Balance after: ${s}`,
    wageAfter: (s: string) => `Payroll after: ${s} / split`,
    squadFullWarning: "Squad is full — release or sell first.",
    shopHim: "Shop him",
    shopHimHint: "Signals availability — expect bids in the next window.",
    quickFlipWarning: "Recently signed — sells at a discount.",
    // v0.2 — coach market + browsing tools
    coaches: "Coaches",
    coachRealTag: "Former pro",
    coachGenTag: "Coach",
    coachBonus: (stat: string) => `Boosts ${stat}`,
    hireCoach: "Hire",
    currentCoach: "Current coach",
    replaceWarning: "Replacing a coach pays one split of severance.",
    searchPlaceholder: "Search players…",
    sortBy: "Sort",
    sortOvr: "Overall",
    sortAge: "Age",
    sortPrice: "Price",
    sortPot: "Potential",
    sortAsc: "Low → high",
    sortDesc: "High → low",
    filterRegion: "Region",
    allRegions: "All regions",
    viewSheet: "View sheet",
    noResults: "No players match the filters.",
    dealsEmpty: "No active deals. Offers land here when a window is open.",
    // v0.3 rep-gated signings (visible lock)
    lockedAtRep: (rep: number) => `Signs at ${rep} reputation`,
    lockedHint: "Players of this level won't join the org yet — reputation opens the door.",
    coachLockedAt: (rep: number) => `Coach hiring unlocks at ${rep} reputation`,
    // v0.3 salary negotiation
    negotiation: {
      title: "Wage talk",
      yourOffer: "Your offer",
      fullAsk: "Pay the ask",
      chance: (pct: number) => `${pct}% to accept`,
      safe: "Safe",
      likely: "Likely",
      risky: "Risky",
      lowball: "Insulting",
      hardened: (n: number) =>
        n === 1 ? "One counter rejected — the ask hardened." : `${n} counters rejected — only the full ask signs now.`,
      savings: (s: string) => `Saves ${s} / split`,
    },
    errors: {
      windowClosed: "The transfer window is closed.",
      alreadySigned: "Already on the squad.",
      squadFull: "Squad is full — release or sell first.",
      unavailable: "Player unavailable.",
      funds: "Not enough money for this deal.",
      loanActive: "No fee transfers while the Backer loan is active.",
      unknown: "That deal is no longer available.",
      locked: "Locked for now.",
      maxed: "Already at the maximum.",
      used: "Already used.",
      restDay: "Not on a rest day.",
      blocked: "Not right now.",
      none: "Nothing to do.",
      invalid: "Invalid selection.",
      repGate: "The org's reputation is too low for a player of this level.",
      negotiationRejected: "Offer rejected — the agent hardened the ask.",
      negotiationLocked: "Negotiations soured — only the full ask signs this window.",
      lowball: "That offer would insult the player.",
      sameDay: "Already scrimmed this team today.",
    },
  },

  finances: {
    title: "Finances",
    balance: "Balance",
    net: "Net / split",
    projected: "Projected after payday",
    income: "In",
    expenses: "Out",
    ledger: "Movements",
    payday: "Payday",
    ledgerKind: {
      prize: "Prize money",
      sponsorBase: "Sponsor payment",
      sponsorBonus: "Sponsor bonus",
      sponsorSigning: "Sponsor signing bonus",
      salary: "Player wages",
      coachSalary: "Coach wages",
      severance: "Severance",
      transferIn: "Transfer fee received",
      transferOut: "Transfer fee paid",
      signingBonus: "Signing bonus",
      releaseFee: "Release fee",
      standInFee: "Emergency stand-in",
      facility: "Facility upgrade",
      upkeep: "Facility upkeep",
      buff: "Staff & boosts",
      loanGrant: "Backer rescue",
      loanGarnish: "Backer repayment",
      loanPayment: "Debt payment",
      fanbase: "Fanbase revenue",
    },
    sponsors: "Sponsors",
    sponsorTier: (t: number) => `Tier ${t}`,
    sponsorObjective: "Objective",
    objective: {
      enterEvents: (n: number) => `Enter ${n}+ events this split (officials count)`,
      regionalTop8: "Reach a regional top-8 this split",
      majorQualify: "Qualify for the Major",
      majorTop4: "Reach the Major top-4",
    },
    onTrack: "On track",
    objectiveHit: "Delivered",
    objectiveMissed: "Missed this split",
    patience: (n: number, max: number) => `Sponsor confidence: ${max - n} of ${max}`,
    patienceWarn: "Another miss and next season's offer drops a tier.",
    offerTitle: "Sponsorship offers",
    perSplitBase: (s: string) => `${s} / split guaranteed`,
    bonusFor: (s: string) => `+${s} per objective hit`,
    backer: "Emergency Backer",
    backerRemaining: (s: string) => `Backer: ${s} to repay`,
    backerLine: (pct: number) => `Repaid from prize money (${pct}%)`,
    // v0.3 debt pay-down
    backerSaleLine: (pct: number) => `Player sales repay ${pct}% automatically`,
    payDebt: "Pay down debt",
    payDebtAll: (s: string) => `Pay it all (${s})`,
    payDebtAmount: "Amount",
    payDebtHint: "Clear the debt to unlock fee transfers and gear purchases.",
    debtCleared: "Debt cleared — the org is free again.",
    backerWarning: "This deal likely triggers the Emergency Backer.",
    backerRescued: "The Backer stepped in — one rescue per career. Going broke again ends it.",
    insolvencyWarning: "The books are failing. A second collapse ends the career.",
    boosts: "Boosts & staff",
    psychologist: "Sports Psychologist",
    psychologistDesc: "+1 Clutch, +1 Consistency while retained. The hire that wins deciding games.",
    bootcamp: "Bootcamp",
    bootcampDesc: "Permanent chemistry bump + a sharper next official event.",
    bootcampUsed: "Bootcamp already run this split.",
    upkeepLabel: (s: string) => `Upkeep ${s} / split`,
    lockedAtRep: (rep: number) => `Unlocks at ${rep} Reputation`,
    activeLabel: "Active",
    ownedLabel: "Owned",
    retainedLabel: "Retained",
    hireLabel: "Retain",
    dropLabel: "End retainer",
    buy: "Purchase",
    // v0.2 gear & staff ladder
    gearLadder: "The org's toolbox",
    gearLadderHint: "Bought in order, unlocked by reputation — a garage org becomes a powerhouse.",
    gear: {
      peripherals: "Pro peripherals",
      monitors: "240Hz monitors",
      pcs: "Tournament PCs",
      perfCenter: "Performance Center",
    },
    gearDesc: {
      peripherals: "Controllers, mice and keyboards the players actually asked for. +5% training.",
      monitors: "No more excuses about frames. +5% training.",
      pcs: "Scrim-server-grade rigs. +10% training and a real team-rating edge.",
      perfCenter: "The full building: analysts' room, gym, review theater. +15% training, elite-level edge.",
    },
    bootcampT1: "Bootcamp",
    bootcampT1Desc: "A week under one roof. Chemistry bump + a light edge next official.",
    bootcampT2: "Structured bootcamp",
    bootcampT2Desc: "Coaching staff, scrim schedule, VOD review. Bigger chemistry bump + a sharp next official.",
    sponsorPerks: "Sponsor perks",
    perkDiscount: (pct: number) => `${pct}% off gear purchases`,
    perkBootcamps: (n: number) => (n === 1 ? "1 free bootcamp / season" : `${n} free bootcamps / season`),
    perkNone: "No perks at this tier",
    freeBootcampLeft: (n: number) => `${n} sponsor-paid bootcamp${n === 1 ? "" : "s"} left this season`,
  },

  standings: {
    title: "Standings",
    splitTab: "Split standings",
    seasonTab: "Road to Worlds",
    majorLine: "Major line",
    worldsLine: "Worlds line",
    clinched: "Clinched",
    contention: "In contention",
    eliminated: "Out of the race",
    ptsShort: "pts",
    remaining: (n: number) => `${n} events left`,
    maxAvailable: (n: number) => `${n} pts still on the board`,
    userChip: "You",
    regionLabel: "Region",
    worldsField: "Worlds field",
    fieldRevealPending: "Revealed when every region concludes",
  },

  news: {
    title: "Inbox",
    unread: (n: number) => `${n} unread`,
    markAllRead: "Mark all read",
    filter: { all: "All", mine: "My org", region: "My region", world: "World", deals: "Deals" },
    wire: "THE WIRE",
    digest: (n: number) => `Around the league: ${n} more moves`,
    // Template keys — params: {player} {org} {from} {to} {fee} {event} {placement} {points} {name} {region} {n}
    tpl: {
      transfer: (p: Record<string, string | number>) => `${p.player} signs with ${p.to}`,
      transferFee: (p: Record<string, string | number>) => `${p.to} lands ${p.player} from ${p.from} (${p.fee})`,
      transferFa: (p: Record<string, string | number>) => `${p.player} finds a home at ${p.to}`,
      userSigned: (p: Record<string, string | number>) => `Official: ${p.player} joins ${p.org}`,
      userSold: (p: Record<string, string | number>) => `${p.player} departs ${p.org} for ${p.to}`,
      userReleased: (p: Record<string, string | number>) => `${p.org} releases ${p.player}`,
      result: (p: Record<string, string | number>) => `${p.org} take ${p.event}`,
      resultUser: (p: Record<string, string | number>) => `${p.event}: you finish ${p.placement}`,
      qualifiedMajor: () => `You're in. The Major awaits.`,
      missedMajor: () => `The Major happens without you this split.`,
      qualifiedWorlds: () => `WORLDS. The org made it.`,
      missedWorlds: () => `The Worlds race ends here this season.`,
      stability: (p: Record<string, string | number>) => `Roster shake-up costs ${p.points} Season Points`,
      contractExpiring: (p: Record<string, string | number>) => `${p.player}'s contract enters its final window`,
      playerLeft: (p: Record<string, string | number>) => `${p.player} walks as a free agent`,
      retirementAnnounce: (p: Record<string, string | number>) => `${p.player} announces his final season`,
      retired: (p: Record<string, string | number>) => `${p.player} hangs up the controller`,
      rookieClass: (p: Record<string, string | number>) => `${p.region} rookie class arrives — ${p.name} headlines`,
      decline: (p: Record<string, string | number>) => `${p.player}, ${p.n}, has lost half a step`,
      breakout: (p: Record<string, string | number>) => `${p.player} is outgrowing everyone's projections`,
      trainingReport: (p: Record<string, string | number>) => `Training report: squad ${p.n} OVR`,
      windowOpen: () => `Transfer window opens — the phones are on`,
      windowClose: () => `Window shut. Rosters are what they are.`,
      windowReport: (p: Record<string, string | number>) => `Window report: ${p.n} moves across the regions`,
      debtCleared: () => `Backer repaid — the org walks free`,
      sponsorSigned: (p: Record<string, string | number>) => `${p.org} announces ${p.name} partnership`,
      sponsorDropped: (p: Record<string, string | number>) => `${p.name} cools on the partnership`,
      repUp: (p: Record<string, string | number>) => `The scene is talking about ${p.org}`,
      repDown: (p: Record<string, string | number>) => `Pundits pile on after ${p.org}'s stumble`,
      starUp: (p: Record<string, string | number>) => `${p.org} reaches ${p.n}-star status`,
      unlock: (p: Record<string, string | number>) => `Unlocked: ${p.name}`,
      unavailable: (p: Record<string, string | number>) => `${p.player} unavailable for ${p.event}`,
      standIn: (p: Record<string, string | number>) => `Emergency stand-in suits up for ${p.event}`,
      backerIn: () => `An emergency backer stabilizes the books`,
      insolvency: () => `The org's finances collapse`,
      seasonChampion: (p: Record<string, string | number>) => `${p.org} are the ${p.event} champions`,
      gearBought: (p: Record<string, string | number>) => `Org upgrade: ${p.name} installed`,
      bootcampRun: (p: Record<string, string | number>): string =>
        Number(p.tier) >= 2 ? "Structured bootcamp concluded" : "Bootcamp week concluded",
      coachHired: (p: Record<string, string | number>) => `${p.org} bring in ${p.coach}`,
      scrimWin: (p: Record<string, string | number>) => `Closed doors: scrim W ${p.a}-${p.b} vs ${p.opponent}`,
      scrimLoss: (p: Record<string, string | number>) => `Closed doors: scrim L ${p.a}-${p.b} vs ${p.opponent}`,
      blockbusterBid: (p: Record<string, string | number>) => `${p.org} table a blockbuster for ${p.player}`,
      flavor1: () => `Desk notes: rotation discipline is the new meta buzzword`,
      flavor2: () => `Scrim servers busy — the whole region is grinding`,
      flavor3: () => `A caster's mic caught a very honest halftime take`,
      flavor4: () => `Ping complaints filed. Ping complaints dismissed.`,
      flavor5: () => `A community montage is doing numbers this week`,
    },
    // v0.2 — body text per template (same params; HQ feed renders these).
    body: {
      transferFee: (p: Record<string, string | number>) =>
        `${p.to} agreed a fee with ${p.from} for ${p.player}. The region's map shifts again.`,
      transferFa: (p: Record<string, string | number>) =>
        `${p.player} had been without an org — ${p.to} moved first. Free-agency value, if the fit works.`,
      userSigned: (p: Record<string, string | number>) =>
        `The paperwork is done: ${p.player} is yours. Chemistry starts at zero — the table only remembers results.`,
      userSold: (p: Record<string, string | number>) =>
        `${p.player} leaves for ${p.to}. The fee lands in the books; the hole in the lineup is yours to solve.`,
      userReleased: (p: Record<string, string | number>) =>
        `${p.org} paid the severance and moved on. ${p.player} joins the free-agent pool.`,
      result: (p: Record<string, string | number>) =>
        `${p.org} closed out ${p.event}. The desk will replay that grand final for weeks.`,
      resultUser: (p: Record<string, string | number>) =>
        `The org's ${p.event} run ends at ${p.placement}. Every placement pays — and the table remembers.`,
      qualifiedMajor: () =>
        `The split standings locked and your name is above the line. Cross-region field, doubled points — the real test.`,
      missedMajor: () =>
        `Below the line when it locked. The next split resets the race — the Worlds points already banked still count.`,
      qualifiedWorlds: () =>
        `A full season of points did it. The biggest field in the game awaits — one bracket for everything.`,
      missedWorlds: () =>
        `The season's points weren't enough. The org watches Worlds from home — and plans the comeback.`,
      stability: (p: Record<string, string | number>) =>
        `Fielding another new face mid-split cost ${p.points} Season Points. Rebuilds belong in the preseason.`,
      contractExpiring: (p: Record<string, string | number>) =>
        `${p.player}'s deal is running out. You hold the exclusive re-sign window through Split 3.`,
      playerLeft: (p: Record<string, string | number>) =>
        `No renewal came, so ${p.player} walked for free. Agents talk — the next negotiation starts from this.`,
      retirementAnnounce: (p: Record<string, string | number>) =>
        `${p.player} will retire at season's end. One more run together — make it count.`,
      retired: (p: Record<string, string | number>) =>
        `${p.player} steps away from the game. The scene is younger — and a little poorer — today.`,
      rookieClass: (p: Record<string, string | number>) =>
        `Fresh names hit the ${p.region} free-agent pool. ${p.name} is the one scouts underline.`,
      decline: (p: Record<string, string | number>) =>
        `Age comes for the mechanics first. ${p.player} is adapting his game — experience keeps paying.`,
      windowOpen: () =>
        `Agents answering, fees moving, rosters unlocked. Deals resolve as the days advance; the window won't wait.`,
      windowReport: (p: Record<string, string | number>) =>
        `${p.n} moves logged before the window shut. The full wire — fees, free agents, every region — is on the HQ.`,
      debtCleared: () =>
        `The last installment cleared the Emergency Backer's books. Fee transfers and gear purchases are open again.`,
      sponsorSigned: (p: Record<string, string | number>) =>
        `${p.org} and ${p.name} signed for the season. Guaranteed base, bonus on the objective — deliver and the tier grows.`,
      unlock: (p: Record<string, string | number>) =>
        `Reputation opened a new door: ${p.name}. The progression track shows what's still ahead.`,
      unavailable: (p: Record<string, string | number>) =>
        `${p.player} can't play ${p.event} — visas, health, life. The sub steps in with his chemistry; without one, a stand-in fills the seat.`,
      standIn: (p: Record<string, string | number>) =>
        `A hired stand-in keeps the org in ${p.event}. Full lineup, zero chemistry — it shows.`,
      backerIn: () =>
        `The floor broke and the Backer's grant landed. Repayment garnishes prize money until cleared. There is no second rescue.`,
      insolvency: () =>
        `The second collapse. Wages unpaid, seats empty, servers dark — the org's story ends in the ledger.`,
      seasonChampion: (p: Record<string, string | number>) =>
        `${p.org} lift the trophy at ${p.event}. The bar for everyone else just moved.`,
      incomingBid: (p: Record<string, string | number>) =>
        `${p.org} want ${p.player} and put money on the table. The decision — and the consequences — are yours.`,
      gearBought: (p: Record<string, string | number>) =>
        `The ${p.name} upgrade is in. Training efficiency ticks up — the players noticed immediately.`,
      bootcampRun: () =>
        `A week under one roof does what no schedule can: the squad plays like it shares a brain. Sharper next official, permanently closer.`,
      coachHired: (p: Record<string, string | number>) =>
        `${p.coach} takes the ${p.org} whiteboard. Development pace and match prep both answer to the bench now.`,
      scrimWin: (p: Record<string, string | number>) =>
        `A tidy closed-doors set against ${p.opponent}. Reps in, chemistry up, nothing leaked to the wire — almost.`,
      scrimLoss: (p: Record<string, string | number>) =>
        `${p.opponent} took the scrim set. Losses behind closed doors are the cheapest lessons in esports.`,
      blockbusterBid: (p: Record<string, string | number>) =>
        `${p.org} moved with real intent for ${p.player}. History wants this transfer — you decide if it happens.`,
      repDown: (p: Record<string, string | number>) =>
        `Expectations were stated and missed; ${p.org}'s standing takes the hit. Reputation is earned back the same way it was built.`,
    },
  },

  club: {
    title: "Club",
    identity: "Identity",
    manager: "Manager",
    founded: "Founded",
    region: "Region",
    reputation: "Reputation",
    repNext: (v: number, label: string) => `Next at ${v}: ${label}`,
    stars: "Team rating",
    starLabel: (n: number) => `${n}-star org`,
    trophies: "Trophy room",
    trophyEmpty: "The shelf is waiting.",
    worldsPedestal: "The Worlds pedestal",
    records: "Records",
    recordPrize: "Total prize money",
    recordSeries: "Series record",
    recordBiggestFee: "Biggest signing",
    recordTitles: "Titles",
    seasonHistory: "Season history",
    editColors: "Re-tint colors",
    progression: "Progression",
    progressionDesc: "Everything still ahead of this org.",
    unlockAt: (v: number) => `Unlocks at ${v} Reputation`,
    unlockWorlds: "Unlocks with a Worlds berth",
    unlockFuture: "Future update",
    unlocked: "Unlocked",
    unlockables: {
      peripherals: "Pro peripherals",
      monitors: "240Hz monitors",
      pcs: "Tournament PCs",
      bootcamp1: "Bootcamp",
      bootcamp2: "Structured bootcamp",
      psychologist: "Sports Psychologist",
      perfCenter: "Performance Center",
      coach: "Coach hiring",
      t2: "Invitational circuit",
      sponsorT2: "Challenger sponsors",
      sponsorT3: "Global sponsors",
      sponsorT4: "Title partners",
      relocation: "Org relocation",
      star5: "5-star status",
    },
    editCrest: "Edit crest",
    settings: "Career settings",
    abandonCareer: "Abandon career",
    abandonConfirm: "This deletes the save permanently. The trophies go with it.",
  },

  event: {
    lobbyTitle: "Event lobby",
    format: "Format",
    formatSwiss: "16-team Swiss → top-8 double elimination",
    formatSingle: "8-team knockout",
    yourSeed: (n: number) => `Seed #${n}`,
    watch: "Play it out",
    instant: "Instant result",
    simToEnd: "Sim to end",
    skipSeries: "Skip series",
    lockIn: "Lock in",
    lineupLocked: "Lineup locked for the event",
    roundLabel: (n: number) => `Round ${n}`,
    swissStage: "Swiss stage",
    playoffs: "Playoffs",
    grandFinal: "Grand Final",
    thirdPlace: "Third place",
    semifinal: "Semifinal",
    quarterfinal: "Quarterfinal",
    upperBracket: "Upper bracket",
    lowerBracket: "Lower bracket",
    game: (n: number) => `Game ${n}`,
    goal: "GOAL",
    overtime: "OVERTIME",
    matchPoint: "Match point",
    deciding: "Deciding game",
    upset: "UPSET",
    seriesWin: (name: string) => `${name} take the series`,
    sweep: "A clean sweep",
    reverseSweep: "REVERSE SWEEP",
    eliminated: "Your run ends here",
    advancing: "Through to the next round",
    champion: (name: string) => `${name} — CHAMPIONS`,
    yourResult: (placement: string) => `Final placement: ${placement}`,
    earned: "Earned",
    unavailableNotice: (player: string) => `${player} can't play this one — next man up.`,
    aiTicker: "Around the bracket",
    speed: "Speed",
    // v0.2 rebuild — live standings, bracket, match center
    standings: "Standings",
    bracket: "Bracket",
    matchCenter: "Match center",
    throughRound: (n: number) => `Through round ${n}`,
    record: "W-L",
    gameDiff: "GD",
    advancedTag: "Through",
    eliminatedTag: "Out",
    liveTag: "LIVE",
    nextUp: "Next up",
    yourMatch: "Your series",
    starOfSeries: (name: string) => `Player of the series: ${name}`,
    scorerLine: (name: string, n: number) => `${name} ×${n}`,
    resultsDigest: "Results digest",
    digestPlacement: "Placement",
    digestPrize: "Prize",
    digestPoints: "Season Points",
    digestRep: "Reputation",
    digestTopScorer: "Top scorer",
    continueToHq: "Back to HQ",
    continueToReview: "Season review",
    fieldTitle: "The field",
    avgOvr: "Avg OVR",
    seedLabel: "Seed",
  },

  spectate: {
    title: "From the couch",
    watchParty: "Watch party",
    digestTitle: "Results digest",
    meaning: "What it means for you",
    followedResult: (org: string, placement: string) => `${org} finish ${placement}`,
  },

  ceremonies: {
    splitRecap: "Split recap",
    saveAndRest: "Save & rest",
    keepGoing: "Continue to the window",
    seasonReview: "Season review",
    seasonGrade: (g: string) => `Season grade: ${g}`,
    expected: (label: string) => `Expected: ${label}`,
    delivered: (label: string) => `Delivered: ${label}`,
    devRecap: "Development",
    bizRecap: "Business",
    rolloverTitle: (label: string) => `${label} begins`,
    rolloverCta: "Start the season",
    worldsChampion: (name: string) => `${name} — WORLD CHAMPIONS`,
    yourTitle: "WORLD CHAMPIONS",
    creditsJourney: "The road so far",
    creditsRoster: "The roster that did it",
    finalWhistle: "Final whistle",
    finalWhistleBody: "The 2026 season closes the book — but not the org's story.",
    insolvencyTitle: "Insolvency",
    insolvencyBody: "The books didn't survive a second collapse. The org's story ends here.",
    legacyTitle: "Career legacy",
    legacyGrade: { legend: "Legend", contender: "Contender", challenger: "Challenger", journeyman: "Journeyman" },
    retire: "Retire",
    retireDesc: "The career is archived — trophies and history stay browsable.",
    infinite: "Endless era",
    infiniteDesc: "The timeline is yours now. No more script — just the sim.",
    infiniteExplainer:
      "From 2027 the world is fully procedural: rookies are generated, veterans retire, history is whatever you make.",
    defendTitle: "Defend the title",
  },

  saves: {
    title: "Careers",
    empty: "Found a new org",
    resume: "Resume",
    archived: "Archived",
    champion: "CHAMPIONS",
    endedInsolvent: "Insolvent",
    endedRetired: "Retired",
    delete: "Delete",
    deleteConfirm: (org: string, n: number) =>
      `Delete ${org}? ${n} season${n === 1 ? "" : "s"} of history disappears. Permanent and local.`,
    lastPlayed: "Last played",
    newCareer: "New career",
    slotsFull: "All three slots are taken.",
  },

  goals: {
    reachMajor: "Reach a Major",
    regionalTop4: "A regional top-4",
    majorTop8: "A Major top-8",
    majorTop4: "A Major top-4",
    qualifyWorlds: "Qualify for Worlds",
    worldsTop4: "A Worlds top-4",
    winMajor: "Win a Major",
    winWorlds: "Win Worlds",
    repRisk: (n: number) => `Your reputation expects it (−${n} if missed)`,
  },

  explainers: {
    skipAll: "Skip all tips",
    gotIt: "Got it",
    hub: {
      title: "This is HQ",
      body: "That orange button runs your career. Everything else is optional depth — the org works even if you only ever press Continue.",
    },
    calendar: {
      title: "The season at a glance",
      body: "Three splits, three regionals each, a Major to close every split. Season Points decide who makes the Major — and Worlds.",
    },
    squad: {
      title: "Your squad",
      body: "Three starters and a sub. Keep a core together and chemistry pays; churn it and the table remembers.",
    },
    training: {
      title: "Training",
      body: "Players grow toward their potential every week. The coach can run this for you — take over any time.",
    },
    market: {
      title: "The market",
      body: "Sign free agents or buy out contracts — only while a window is open. Every price shows its math.",
    },
    window: {
      title: "Transfer window",
      body: "Windows sit between splits (plus one final call before Worlds). Deals resolve when you advance the week.",
    },
    finances: {
      title: "The books",
      body: "Prizes and sponsors in, wages and upkeep out, payday every split. Go broke once and a backer saves you. Once.",
    },
    standings: {
      title: "The cut-line",
      body: "The dashed line is the qualification cut. Everything the org fights for is measured against it.",
    },
    sponsor: {
      title: "Sponsors",
      body: "Guaranteed money each split, a bonus if you hit the objective. Missing never costs cash — repeated misses cost the renewal tier.",
    },
    randomEvent: {
      title: "Next man up",
      body: "Sometimes a starter can't play — visas, health, life. A sub steps in with his chemistry; without one, a hired stand-in keeps you in the bracket.",
    },
    worldsRace: {
      title: "The Worlds race",
      body: "Season Points from every regional and Major stack all year. Finish above your region's line and the biggest stage opens.",
    },
    rollover: {
      title: "Season rollover",
      body: "Ages tick, contracts count down, the world re-shuffles toward its history — unless you already changed it.",
    },
  },

  // v0.3 org sheet — any AI org's roster, opened from standings/events/market.
  orgSheet: {
    roster: "Roster",
    coach: "Coach",
    noCoach: "No coach",
    points: "Season Points",
    viewTeam: "View team",
    prestige: (n: number) => `Prestige ${n}`,
  },

  common: {
    ovr: "OVR",
    pot: "POT",
    ovrShort: (n: number) => `${n} OVR`,
    starsShort: (n: number) => `${n}★`,
    rep: "Rep",
    reputation: "Reputation",
    seasonPoints: "Season Points",
    prize: "Prize",
    confirm: "Confirm",
    cancel: "Cancel",
    back: "Back",
    next: "Next",
    close: "Close",
    locked: "Locked",
    free: "Free",
    perSplit: "/ split",
    you: "You",
    placement: {
      champion: "Champions",
      runner_up: "Runners-up",
      third: "3rd place",
      fourth: "4th place",
      top4: "Top 4",
      top6: "Top 6",
      top8: "Top 8",
      swiss_exit: "Swiss exit",
    },
    tier: {
      t3: "Community Cup",
      t2: "Invitational",
      regional: "Regional",
      major: "Major",
      worlds: "Worlds",
    },
    difficultyNote: "Difficulty shapes opponents and money — never who you can sign.",
  },
};

export type CareerCopy = typeof CAREER_EN;
